/*****************************************************************************

 @(#) src/snmp/isismib.h

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2015  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 *****************************************************************************/

#ifndef __LOCAL_ISISMIB_H__
#define __LOCAL_ISISMIB_H__

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct isisMIB_data {
	struct isisMIB_data *isisMIB_old;
	uint isisMIB_rsvs;
	uint isisMIB_tsts;
	uint isisMIB_sets;
	uint isisMIB_request;
	long isisSysVersion;		/* ReadOnly */
	long isisSysLevelType;		/* ReadWrite */
	uint8_t *isisSysID;		/* ReadWrite */
	size_t isisSysIDLen;
	ulong isisSysMaxPathSplits;	/* ReadWrite */
	ulong isisSysMaxLSPGenInt;	/* ReadWrite */
	ulong isisSysPollESHelloRate;	/* ReadWrite */
	ulong isisSysWaitTime;		/* ReadWrite */
	long isisSysAdminState;		/* ReadWrite */
	long isisSysL2toL1Leaking;	/* ReadWrite */
	ulong isisSysMaxAge;		/* ReadWrite */
	ulong isisSysReceiveLSPBufferSize;	/* ReadWrite */
	uint8_t *isisSysProtSupported;	/* ReadOnly */
	size_t isisSysProtSupportedLen;
	long isisSysNotificationEnable;	/* ReadWrite */
	ulong isisNextCircIndex;	/* ReadOnly */
};
struct isisManAreaAddrTable_data {
	struct isisManAreaAddrTable_data *isisManAreaAddrTable_old;
	uint isisManAreaAddrTable_rsvs;
	uint isisManAreaAddrTable_tsts;
	uint isisManAreaAddrTable_sets;
	uint isisManAreaAddrTable_request;
	uint isisManAreaAddrTable_refs;
	uint isisManAreaAddrTable_id;
	uint8_t *isisManAreaAddr;	/* NoAccess */
	size_t isisManAreaAddrLen;
	long isisManAreaAddrExistState;	/* Create */
};
struct isisAreaAddrTable_data {
	struct isisAreaAddrTable_data *isisAreaAddrTable_old;
	uint isisAreaAddrTable_rsvs;
	uint isisAreaAddrTable_tsts;
	uint isisAreaAddrTable_sets;
	uint isisAreaAddrTable_request;
	uint isisAreaAddrTable_refs;
	uint isisAreaAddrTable_id;
	uint8_t *isisAreaAddr;		/* ReadOnly */
	size_t isisAreaAddrLen;
};
struct isisSummAddrTable_data {
	struct isisSummAddrTable_data *isisSummAddrTable_old;
	uint isisSummAddrTable_rsvs;
	uint isisSummAddrTable_tsts;
	uint isisSummAddrTable_sets;
	uint isisSummAddrTable_request;
	uint isisSummAddrTable_refs;
	uint isisSummAddrTable_id;
	long isisSummAddressType;	/* NoAccess */
	uint8_t *isisSummAddress;	/* NoAccess */
	size_t isisSummAddressLen;
	ulong isisSummAddrPrefixLen;	/* NoAccess */
	long isisSummAddrExistState;	/* Create */
	ulong isisSummAddrMetric;	/* Create */
	ulong isisSummAddrFullMetric;	/* Create */
};
struct isisRedistributeAddrTable_data {
	struct isisRedistributeAddrTable_data *isisRedistributeAddrTable_old;
	uint isisRedistributeAddrTable_rsvs;
	uint isisRedistributeAddrTable_tsts;
	uint isisRedistributeAddrTable_sets;
	uint isisRedistributeAddrTable_request;
	uint isisRedistributeAddrTable_refs;
	uint isisRedistributeAddrTable_id;
	long isisRedistributeAddrType;	/* NoAccess */
	uint8_t *isisRedistributeAddrAddress;	/* NoAccess */
	size_t isisRedistributeAddrAddressLen;
	ulong isisRedistributeAddrPrefixLen;	/* NoAccess */
	long isisRedistributeAddrExistState;	/* Create */
};
struct isisRouterTable_data {
	struct isisRouterTable_data *isisRouterTable_old;
	uint isisRouterTable_rsvs;
	uint isisRouterTable_tsts;
	uint isisRouterTable_sets;
	uint isisRouterTable_request;
	uint isisRouterTable_refs;
	uint isisRouterTable_id;
	uint8_t *isisRouterSysID;	/* NoAccess */
	size_t isisRouterSysIDLen;
	long isisRouterLevel;		/* NoAccess */
	uint8_t *isisRouterHostName;	/* ReadOnly */
	size_t isisRouterHostNameLen;
	ulong isisRouterID;		/* ReadOnly */
};
struct isisSysLevelTable_data {
	struct isisSysLevelTable_data *isisSysLevelTable_old;
	uint isisSysLevelTable_rsvs;
	uint isisSysLevelTable_tsts;
	uint isisSysLevelTable_sets;
	uint isisSysLevelTable_request;
	uint isisSysLevelTable_refs;
	uint isisSysLevelTable_id;
	long isisSysLevelIndex;		/* NoAccess */
	ulong isisSysLevelOrigLSPBuffSize;	/* ReadWrite */
	ulong isisSysLevelMinLSPGenInt;	/* ReadWrite */
	long isisSysLevelState;		/* ReadOnly */
	long isisSysLevelSetOverload;	/* ReadWrite */
	ulong isisSysLevelSetOverloadUntil;	/* ReadWrite */
	long isisSysLevelMetricStyle;	/* ReadWrite */
	long isisSysLevelSPFConsiders;	/* ReadWrite */
	long isisSysLevelTEEnabled;	/* ReadWrite */
};
struct isisCircTable_data {
	struct isisCircTable_data *isisCircTable_old;
	uint isisCircTable_rsvs;
	uint isisCircTable_tsts;
	uint isisCircTable_sets;
	uint isisCircTable_request;
	uint isisCircTable_refs;
	uint isisCircTable_id;
	ulong isisCircIndex;		/* NoAccess */
	long isisCircIfIndex;		/* Create */
	long isisCircAdminState;	/* Create */
	long isisCircExistState;	/* Create */
	long isisCircType;		/* Create */
	long isisCircExtDomain;		/* Create */
	long isisCircLevelType;		/* Create */
	long isisCircPassiveCircuit;	/* Create */
	long isisCircMeshGroupEnabled;	/* Create */
	ulong isisCircMeshGroup;	/* Create */
	long isisCircSmallHellos;	/* Create */
	long isisCircLastUpTime;	/* ReadOnly */
	long isisCirc3WayEnabled;	/* Create */
	ulong isisCircExtendedCircID;	/* Create */
};
struct isisCircLevelTable_data {
	struct isisCircLevelTable_data *isisCircLevelTable_old;
	uint isisCircLevelTable_rsvs;
	uint isisCircLevelTable_tsts;
	uint isisCircLevelTable_sets;
	uint isisCircLevelTable_request;
	uint isisCircLevelTable_refs;
	uint isisCircLevelTable_id;
	ulong isisCircIndex;		/* NoAccess */
	long isisCircLevelIndex;	/* NoAccess */
	ulong isisCircLevelMetric;	/* ReadWrite */
	ulong isisCircLevelWideMetric;	/* ReadWrite */
	ulong isisCircLevelISPriority;	/* ReadWrite */
	ulong isisCircLevelIDOctet;	/* ReadOnly */
	uint8_t *isisCircLevelID;	/* ReadOnly */
	size_t isisCircLevelIDLen;
	uint8_t *isisCircLevelDesIS;	/* ReadOnly */
	size_t isisCircLevelDesISLen;
	ulong isisCircLevelHelloMultiplier;	/* ReadWrite */
	ulong isisCircLevelHelloTimer;	/* ReadWrite */
	ulong isisCircLevelDRHelloTimer;	/* ReadWrite */
	ulong isisCircLevelLSPThrottle;	/* ReadWrite */
	ulong isisCircLevelMinLSPRetransInt;	/* ReadWrite */
	ulong isisCircLevelCSNPInterval;	/* ReadWrite */
	ulong isisCircLevelPartSNPInterval;	/* ReadWrite */
};
struct isisSystemCounterTable_data {
	struct isisSystemCounterTable_data *isisSystemCounterTable_old;
	uint isisSystemCounterTable_rsvs;
	uint isisSystemCounterTable_tsts;
	uint isisSystemCounterTable_sets;
	uint isisSystemCounterTable_request;
	uint isisSystemCounterTable_refs;
	uint isisSystemCounterTable_id;
	long isisSysStatLevel;		/* NoAccess */
	long isisSysStatCorrLSPs;	/* ReadOnly */
	long isisSysStatAuthTypeFails;	/* ReadOnly */
	long isisSysStatAuthFails;	/* ReadOnly */
	long isisSysStatLSPDbaseOloads;	/* ReadOnly */
	long isisSysStatManAddrDropFromAreas;	/* ReadOnly */
	long isisSysStatAttmptToExMaxSeqNums;	/* ReadOnly */
	long isisSysStatSeqNumSkips;	/* ReadOnly */
	long isisSysStatOwnLSPPurges;	/* ReadOnly */
	long isisSysStatIDFieldLenMismatches;	/* ReadOnly */
	long isisSysStatPartChanges;	/* ReadOnly */
	long isisSysStatSPFRuns;	/* ReadOnly */
	long isisSysStatLSPErrors;	/* ReadOnly */
};
struct isisCircuitCounterTable_data {
	struct isisCircuitCounterTable_data *isisCircuitCounterTable_old;
	uint isisCircuitCounterTable_rsvs;
	uint isisCircuitCounterTable_tsts;
	uint isisCircuitCounterTable_sets;
	uint isisCircuitCounterTable_request;
	uint isisCircuitCounterTable_refs;
	uint isisCircuitCounterTable_id;
	ulong isisCircIndex;		/* NoAccess */
	long isisCircuitType;		/* NoAccess */
	long isisCircAdjChanges;	/* ReadOnly */
	ulong isisCircNumAdj;		/* ReadOnly */
	long isisCircInitFails;		/* ReadOnly */
	long isisCircRejAdjs;		/* ReadOnly */
	long isisCircIDFieldLenMismatches;	/* ReadOnly */
	long isisCircMaxAreaAddrMismatches;	/* ReadOnly */
	long isisCircAuthTypeFails;	/* ReadOnly */
	long isisCircAuthFails;		/* ReadOnly */
	long isisCircLANDesISChanges;	/* ReadOnly */
};
struct isisPacketCounterTable_data {
	struct isisPacketCounterTable_data *isisPacketCounterTable_old;
	uint isisPacketCounterTable_rsvs;
	uint isisPacketCounterTable_tsts;
	uint isisPacketCounterTable_sets;
	uint isisPacketCounterTable_request;
	uint isisPacketCounterTable_refs;
	uint isisPacketCounterTable_id;
	ulong isisCircIndex;		/* NoAccess */
	long isisPacketCountLevel;	/* NoAccess */
	long isisPacketCountDirection;	/* NoAccess */
	long isisPacketCountIIHello;	/* ReadOnly */
	long isisPacketCountISHello;	/* ReadOnly */
	long isisPacketCountESHello;	/* ReadOnly */
	long isisPacketCountLSP;	/* ReadOnly */
	long isisPacketCountCSNP;	/* ReadOnly */
	long isisPacketCountPSNP;	/* ReadOnly */
	long isisPacketCountUnknown;	/* ReadOnly */
};
struct isisISAdjTable_data {
	struct isisISAdjTable_data *isisISAdjTable_old;
	uint isisISAdjTable_rsvs;
	uint isisISAdjTable_tsts;
	uint isisISAdjTable_sets;
	uint isisISAdjTable_request;
	uint isisISAdjTable_refs;
	uint isisISAdjTable_id;
	ulong isisCircIndex;		/* NoAccess */
	ulong isisISAdjIndex;		/* NoAccess */
	long isisISAdjState;		/* ReadOnly */
	long isisISAdj3WayState;	/* ReadOnly */
	uint8_t *isisISAdjNeighSNPAAddress;	/* ReadOnly */
	size_t isisISAdjNeighSNPAAddressLen;
	long isisISAdjNeighSysType;	/* ReadOnly */
	uint8_t *isisISAdjNeighSysID;	/* ReadOnly */
	size_t isisISAdjNeighSysIDLen;
	ulong isisISAdjNbrExtendedCircID;	/* ReadOnly */
	long isisISAdjUsage;		/* ReadOnly */
	ulong isisISAdjHoldTimer;	/* ReadOnly */
	ulong isisISAdjNeighPriority;	/* ReadOnly */
	long isisISAdjLastUpTime;	/* ReadOnly */
};
struct isisISAdjAreaAddrTable_data {
	struct isisISAdjAreaAddrTable_data *isisISAdjAreaAddrTable_old;
	uint isisISAdjAreaAddrTable_rsvs;
	uint isisISAdjAreaAddrTable_tsts;
	uint isisISAdjAreaAddrTable_sets;
	uint isisISAdjAreaAddrTable_request;
	uint isisISAdjAreaAddrTable_refs;
	uint isisISAdjAreaAddrTable_id;
	ulong isisCircIndex;		/* NoAccess */
	ulong isisISAdjIndex;		/* NoAccess */
	ulong isisISAdjAreaAddrIndex;	/* NoAccess */
	uint8_t *isisISAdjAreaAddress;	/* ReadOnly */
	size_t isisISAdjAreaAddressLen;
};
struct isisISAdjIPAddrTable_data {
	struct isisISAdjIPAddrTable_data *isisISAdjIPAddrTable_old;
	uint isisISAdjIPAddrTable_rsvs;
	uint isisISAdjIPAddrTable_tsts;
	uint isisISAdjIPAddrTable_sets;
	uint isisISAdjIPAddrTable_request;
	uint isisISAdjIPAddrTable_refs;
	uint isisISAdjIPAddrTable_id;
	ulong isisCircIndex;		/* NoAccess */
	ulong isisISAdjIndex;		/* NoAccess */
	ulong isisISAdjIPAddrIndex;	/* NoAccess */
	long isisISAdjIPAddrType;	/* ReadOnly */
	uint8_t *isisISAdjIPAddrAddress;	/* ReadOnly */
	size_t isisISAdjIPAddrAddressLen;
};
struct isisISAdjProtSuppTable_data {
	struct isisISAdjProtSuppTable_data *isisISAdjProtSuppTable_old;
	uint isisISAdjProtSuppTable_rsvs;
	uint isisISAdjProtSuppTable_tsts;
	uint isisISAdjProtSuppTable_sets;
	uint isisISAdjProtSuppTable_request;
	uint isisISAdjProtSuppTable_refs;
	uint isisISAdjProtSuppTable_id;
	ulong isisCircIndex;		/* NoAccess */
	ulong isisISAdjIndex;		/* NoAccess */
	long isisISAdjProtSuppProtocol;	/* ReadOnly */
};
struct isisRATable_data {
	struct isisRATable_data *isisRATable_old;
	uint isisRATable_rsvs;
	uint isisRATable_tsts;
	uint isisRATable_sets;
	uint isisRATable_request;
	uint isisRATable_refs;
	uint isisRATable_id;
	ulong isisCircIndex;		/* NoAccess */
	ulong isisRAIndex;		/* NoAccess */
	long isisRAExistState;		/* Create */
	long isisRAAdminState;		/* Create */
	uint8_t *isisRAAddrPrefix;	/* Create */
	size_t isisRAAddrPrefixLen;
	long isisRAMapType;		/* Create */
	ulong isisRAMetric;		/* Create */
	long isisRAMetricType;		/* Create */
	uint8_t *isisRASNPAAddress;	/* Create */
	size_t isisRASNPAAddressLen;
	uint8_t *isisRASNPAMask;	/* Create */
	size_t isisRASNPAMaskLen;
	uint8_t *isisRASNPAPrefix;	/* Create */
	size_t isisRASNPAPrefixLen;
	long isisRAType;		/* Create */
};
struct isisIPRATable_data {
	struct isisIPRATable_data *isisIPRATable_old;
	uint isisIPRATable_rsvs;
	uint isisIPRATable_tsts;
	uint isisIPRATable_sets;
	uint isisIPRATable_request;
	uint isisIPRATable_refs;
	uint isisIPRATable_id;
	long isisSysLevelIndex;		/* NoAccess */
	long isisIPRADestType;		/* NoAccess */
	uint8_t *isisIPRADest;		/* NoAccess */
	size_t isisIPRADestLen;
	ulong isisIPRADestPrefixLen;	/* NoAccess */
	ulong isisIPRANextHopIndex;	/* NoAccess */
	long isisIPRANextHopType;	/* Create */
	uint8_t *isisIPRANextHop;	/* Create */
	size_t isisIPRANextHopLen;
	long isisIPRAType;		/* Create */
	long isisIPRAExistState;	/* Create */
	long isisIPRAAdminState;	/* Create */
	ulong isisIPRAMetric;		/* Create */
	long isisIPRAMetricType;	/* Create */
	ulong isisIPRAFullMetric;	/* Create */
	uint8_t *isisIPRASNPAAddress;	/* Create */
	size_t isisIPRASNPAAddressLen;
	long isisIPRASourceType;	/* ReadOnly */
};
struct isisLSPSummaryTable_data {
	struct isisLSPSummaryTable_data *isisLSPSummaryTable_old;
	uint isisLSPSummaryTable_rsvs;
	uint isisLSPSummaryTable_tsts;
	uint isisLSPSummaryTable_sets;
	uint isisLSPSummaryTable_request;
	uint isisLSPSummaryTable_refs;
	uint isisLSPSummaryTable_id;
	long isisLSPLevel;		/* NoAccess */
	uint8_t *isisLSPID;		/* NoAccess */
	size_t isisLSPIDLen;
	ulong isisLSPSeq;		/* ReadOnly */
	long isisLSPZeroLife;		/* ReadOnly */
	ulong isisLSPChecksum;		/* ReadOnly */
	ulong isisLSPLifetimeRemain;	/* ReadOnly */
	ulong isisLSPPDULength;		/* ReadOnly */
	ulong isisLSPAttributes;	/* ReadOnly */
};
struct isisLSPTLVTable_data {
	struct isisLSPTLVTable_data *isisLSPTLVTable_old;
	uint isisLSPTLVTable_rsvs;
	uint isisLSPTLVTable_tsts;
	uint isisLSPTLVTable_sets;
	uint isisLSPTLVTable_request;
	uint isisLSPTLVTable_refs;
	uint isisLSPTLVTable_id;
	long isisLSPLevel;		/* NoAccess */
	uint8_t *isisLSPID;		/* NoAccess */
	size_t isisLSPIDLen;
	ulong isisLSPTLVIndex;		/* NoAccess */
	ulong isisLSPTLVSeq;		/* ReadOnly */
	ulong isisLSPTLVChecksum;	/* ReadOnly */
	ulong isisLSPTLVType;		/* ReadOnly */
	ulong isisLSPTLVLen;		/* ReadOnly */
	uint8_t *isisLSPTLVValue;	/* ReadOnly */
	size_t isisLSPTLVValueLen;
};

/* storage declarations */
extern struct isisMIB_data *isisMIBStorage;
extern struct header_complex_index *isisManAreaAddrTableStorage;
extern struct header_complex_index *isisAreaAddrTableStorage;
extern struct header_complex_index *isisSummAddrTableStorage;
extern struct header_complex_index *isisRedistributeAddrTableStorage;
extern struct header_complex_index *isisRouterTableStorage;
extern struct header_complex_index *isisSysLevelTableStorage;
extern struct header_complex_index *isisCircTableStorage;
extern struct header_complex_index *isisCircLevelTableStorage;
extern struct header_complex_index *isisSystemCounterTableStorage;
extern struct header_complex_index *isisCircuitCounterTableStorage;
extern struct header_complex_index *isisPacketCounterTableStorage;
extern struct header_complex_index *isisISAdjTableStorage;
extern struct header_complex_index *isisISAdjAreaAddrTableStorage;
extern struct header_complex_index *isisISAdjIPAddrTableStorage;
extern struct header_complex_index *isisISAdjProtSuppTableStorage;
extern struct header_complex_index *isisRATableStorage;
extern struct header_complex_index *isisIPRATableStorage;
extern struct header_complex_index *isisLSPSummaryTableStorage;
extern struct header_complex_index *isisLSPTLVTableStorage;

/* enum definitions from the covered mib sections */
#define ISISSYSVERSION_UNKNOWN                   0
#define ISISSYSVERSION_ONE                       1

#define ISISSYSLEVELTYPE_LEVEL1                  1
#define ISISSYSLEVELTYPE_LEVEL2                  2
#define ISISSYSLEVELTYPE_LEVEL1AND2              3

#define ISISSYSADMINSTATE_ON                     1
#define ISISSYSADMINSTATE_OFF                    2

#define ISISSYSL2TOL1LEAKING_TRUE                1
#define ISISSYSL2TOL1LEAKING_FALSE               2

#define ISISSYSPROTSUPPORTED_ISO8473             0
#define ISISSYSPROTSUPPORTED_IPV4                1
#define ISISSYSPROTSUPPORTED_IPV6                2

#define ISISSYSNOTIFICATIONENABLE_TRUE           1
#define ISISSYSNOTIFICATIONENABLE_FALSE          2

#define ISISSUMMADDRESSTYPE_UNKNOWN              0
#define ISISSUMMADDRESSTYPE_IPV4                 1
#define ISISSUMMADDRESSTYPE_IPV6                 2
#define ISISSUMMADDRESSTYPE_IPV4Z                3
#define ISISSUMMADDRESSTYPE_IPV6Z                4
#define ISISSUMMADDRESSTYPE_DNS                  16

#define ISISREDISTRIBUTEADDRTYPE_UNKNOWN         0
#define ISISREDISTRIBUTEADDRTYPE_IPV4            1
#define ISISREDISTRIBUTEADDRTYPE_IPV6            2
#define ISISREDISTRIBUTEADDRTYPE_IPV4Z           3
#define ISISREDISTRIBUTEADDRTYPE_IPV6Z           4
#define ISISREDISTRIBUTEADDRTYPE_DNS             16

#define ISISROUTERLEVEL_AREA                     1
#define ISISROUTERLEVEL_DOMAIN                   2

#define ISISSYSLEVELINDEX_AREA                   1
#define ISISSYSLEVELINDEX_DOMAIN                 2

#define ISISSYSLEVELSTATE_OFF                    1
#define ISISSYSLEVELSTATE_ON                     2
#define ISISSYSLEVELSTATE_WAITING                3
#define ISISSYSLEVELSTATE_OVERLOADED             4

#define ISISSYSLEVELSETOVERLOAD_TRUE             1
#define ISISSYSLEVELSETOVERLOAD_FALSE            2

#define ISISSYSLEVELMETRICSTYLE_NARROW           1
#define ISISSYSLEVELMETRICSTYLE_WIDE             2
#define ISISSYSLEVELMETRICSTYLE_BOTH             3

#define ISISSYSLEVELSPFCONSIDERS_NARROW          1
#define ISISSYSLEVELSPFCONSIDERS_WIDE            2
#define ISISSYSLEVELSPFCONSIDERS_BOTH            3

#define ISISSYSLEVELTEENABLED_TRUE               1
#define ISISSYSLEVELTEENABLED_FALSE              2

#define ISISCIRCADMINSTATE_ON                    1
#define ISISCIRCADMINSTATE_OFF                   2

#define ISISCIRCTYPE_BROADCAST                   1
#define ISISCIRCTYPE_PTTOPT                      2
#define ISISCIRCTYPE_STATICIN                    3
#define ISISCIRCTYPE_STATICOUT                   4
#define ISISCIRCTYPE_DA                          5

#define ISISCIRCEXTDOMAIN_TRUE                   1
#define ISISCIRCEXTDOMAIN_FALSE                  2

#define ISISCIRCLEVELTYPE_LEVEL1                 1
#define ISISCIRCLEVELTYPE_LEVEL2                 2
#define ISISCIRCLEVELTYPE_LEVEL1AND2             3

#define ISISCIRCPASSIVECIRCUIT_TRUE              1
#define ISISCIRCPASSIVECIRCUIT_FALSE             2

#define ISISCIRCMESHGROUPENABLED_INACTIVE        1
#define ISISCIRCMESHGROUPENABLED_BLOCKED         2
#define ISISCIRCMESHGROUPENABLED_SET             3

#define ISISCIRCSMALLHELLOS_TRUE                 1
#define ISISCIRCSMALLHELLOS_FALSE                2

#define ISISCIRC3WAYENABLED_TRUE                 1
#define ISISCIRC3WAYENABLED_FALSE                2

#define ISISCIRCLEVELINDEX_AREA                  1
#define ISISCIRCLEVELINDEX_DOMAIN                2

#define ISISSYSSTATLEVEL_AREA                    1
#define ISISSYSSTATLEVEL_DOMAIN                  2

#define ISISCIRCUITTYPE_LANLEVEL1                1
#define ISISCIRCUITTYPE_LANLEVEL2                2
#define ISISCIRCUITTYPE_P2PCIRCUIT               3

#define ISISPACKETCOUNTLEVEL_AREA                1
#define ISISPACKETCOUNTLEVEL_DOMAIN              2

#define ISISPACKETCOUNTDIRECTION_SENDING         1
#define ISISPACKETCOUNTDIRECTION_RECEIVING       2

#define ISISISADJSTATE_DOWN                      1
#define ISISISADJSTATE_INITIALIZING              2
#define ISISISADJSTATE_UP                        3
#define ISISISADJSTATE_FAILED                    4

#define ISISISADJ3WAYSTATE_UP                    0
#define ISISISADJ3WAYSTATE_INITIALIZING          1
#define ISISISADJ3WAYSTATE_DOWN                  2
#define ISISISADJ3WAYSTATE_FAILED                3

#define ISISISADJNEIGHSYSTYPE_L1INTERMEDIATESYSTEM 1
#define ISISISADJNEIGHSYSTYPE_L2INTERMEDIATESYSTEM 2
#define ISISISADJNEIGHSYSTYPE_L1L2INTERMEDIATESYSTEM 3
#define ISISISADJNEIGHSYSTYPE_UNKNOWN            4

#define ISISISADJUSAGE_LEVEL1                    1
#define ISISISADJUSAGE_LEVEL2                    2
#define ISISISADJUSAGE_LEVEL1AND2                3

#define ISISISADJIPADDRTYPE_UNKNOWN              0
#define ISISISADJIPADDRTYPE_IPV4                 1
#define ISISISADJIPADDRTYPE_IPV6                 2
#define ISISISADJIPADDRTYPE_IPV4Z                3
#define ISISISADJIPADDRTYPE_IPV6Z                4
#define ISISISADJIPADDRTYPE_DNS                  16

#define ISISISADJPROTSUPPPROTOCOL_ISO8473        129
#define ISISISADJPROTSUPPPROTOCOL_IPV6           142
#define ISISISADJPROTSUPPPROTOCOL_IP             204

#define ISISRAADMINSTATE_ON                      1
#define ISISRAADMINSTATE_OFF                     2

#define ISISRAMAPTYPE_NONE                       1
#define ISISRAMAPTYPE_EXPLICIT                   2
#define ISISRAMAPTYPE_EXTRACTIDI                 3
#define ISISRAMAPTYPE_EXTRACTDSP                 4

#define ISISRAMETRICTYPE_INTERNAL                1
#define ISISRAMETRICTYPE_EXTERNAL                2

#define ISISRATYPE_MANUAL                        1
#define ISISRATYPE_AUTOMATIC                     2

#define ISISSYSLEVELINDEX_AREA                   1
#define ISISSYSLEVELINDEX_DOMAIN                 2

#define ISISIPRADESTTYPE_UNKNOWN                 0
#define ISISIPRADESTTYPE_IPV4                    1
#define ISISIPRADESTTYPE_IPV6                    2
#define ISISIPRADESTTYPE_IPV4Z                   3
#define ISISIPRADESTTYPE_IPV6Z                   4
#define ISISIPRADESTTYPE_DNS                     16

#define ISISIPRANEXTHOPTYPE_UNKNOWN              0
#define ISISIPRANEXTHOPTYPE_IPV4                 1
#define ISISIPRANEXTHOPTYPE_IPV6                 2
#define ISISIPRANEXTHOPTYPE_IPV4Z                3
#define ISISIPRANEXTHOPTYPE_IPV6Z                4
#define ISISIPRANEXTHOPTYPE_DNS                  16

#define ISISIPRATYPE_MANUAL                      1
#define ISISIPRATYPE_AUTOMATIC                   2

#define ISISIPRAADMINSTATE_ON                    1
#define ISISIPRAADMINSTATE_OFF                   2

#define ISISIPRAMETRICTYPE_INTERNAL              1
#define ISISIPRAMETRICTYPE_EXTERNAL              2

#define ISISIPRASOURCETYPE_STATIC                1
#define ISISIPRASOURCETYPE_DIRECT                2
#define ISISIPRASOURCETYPE_OSPFV2                3
#define ISISIPRASOURCETYPE_OSPFV3                4
#define ISISIPRASOURCETYPE_ISIS                  5
#define ISISIPRASOURCETYPE_RIP                   6
#define ISISIPRASOURCETYPE_IGRP                  7
#define ISISIPRASOURCETYPE_EIGRP                 8
#define ISISIPRASOURCETYPE_BGP                   9
#define ISISIPRASOURCETYPE_OTHER                 10

#define ISISLSPLEVEL_AREA                        1
#define ISISLSPLEVEL_DOMAIN                      2

#define ISISLSPZEROLIFE_TRUE                     1
#define ISISLSPZEROLIFE_FALSE                    2

#define ISISLSPLEVEL_AREA                        1
#define ISISLSPLEVEL_DOMAIN                      2

#define ISISNOTIFICATIONSYSLEVELINDEX_LEVEL1     1
#define ISISNOTIFICATIONSYSLEVELINDEX_LEVEL2     2
#define ISISNOTIFICATIONSYSLEVELINDEX_LEVEL1AND2 3

#define ISISADJSTATE_DOWN                        1
#define ISISADJSTATE_INITIALIZING                2
#define ISISADJSTATE_UP                          3
#define ISISADJSTATE_FAILED                      4

/* notifications */
extern oid isisDatabaseOverload_oid[9];
extern oid isisManualAddressDrops_oid[9];
extern oid isisCorruptedLSPDetected_oid[9];
extern oid isisAttemptToExceedMaxSequence_oid[9];
extern oid isisIDLenMismatch_oid[9];
extern oid isisMaxAreaAddressesMismatch_oid[9];
extern oid isisOwnLSPPurge_oid[9];
extern oid isisSequenceNumberSkip_oid[9];
extern oid isisAuthenticationTypeFailure_oid[9];
extern oid isisAuthenticationFailure_oid[9];
extern oid isisVersionSkew_oid[9];
extern oid isisAreaMismatch_oid[9];
extern oid isisRejectedAdjacency_oid[9];
extern oid isisLSPTooLargeToPropagate_oid[9];
extern oid isisOrigLSPBuffSizeMismatch_oid[9];
extern oid isisProtocolsSupportedMismatch_oid[9];
extern oid isisAdjacencyChange_oid[9];
extern oid isisLSPErrorDetected_oid[9];

/* scalars accessible only for notify */
extern oid isisNotificationSysLevelIndex_oid[11];
extern oid isisNotificationCircIfIndex_oid[11];
extern oid isisPduLspId_oid[11];
extern oid isisPduFragment_oid[11];
extern oid isisPduFieldLen_oid[11];
extern oid isisPduMaxAreaAddress_oid[11];
extern oid isisPduProtocolVersion_oid[11];
extern oid isisPduLspSize_oid[11];
extern oid isisPduOriginatingBufferSize_oid[11];
extern oid isisPduBufferSize_oid[11];
extern oid isisPduProtocolsSupported_oid[11];
extern oid isisAdjState_oid[11];
extern oid isisErrorOffset_oid[11];
extern oid isisErrorTLVType_oid[11];
extern oid isisNotificationAreaAddress_oid[11];

/* object id definitions */
extern oid isisCompliance_oid[10];
extern oid isisAdvancedCompliance_oid[10];
extern oid isisReadOnlyCompliance_oid[10];
extern oid isisSystemGroup_oid[10];
extern oid isisCircuitGroup_oid[10];
extern oid isisISAdjGroup_oid[10];
extern oid isisNotificationObjectGroup_oid[10];
extern oid isisNotificationGroup_oid[10];
extern oid isisISPDUCounterGroup_oid[10];
extern oid isisRATableGroup_oid[10];
extern oid isisISIPRADestGroup_oid[10];
extern oid isisLSPGroup_oid[10];

/* function prototypes */
/* trap function prototypes */
extern void send_isisDatabaseOverload_v2trap(struct variable_list *);
extern void send_isisManualAddressDrops_v2trap(struct variable_list *);
extern void send_isisCorruptedLSPDetected_v2trap(struct variable_list *);
extern void send_isisAttemptToExceedMaxSequence_v2trap(struct variable_list *);
extern void send_isisIDLenMismatch_v2trap(struct variable_list *);
extern void send_isisMaxAreaAddressesMismatch_v2trap(struct variable_list *);
extern void send_isisOwnLSPPurge_v2trap(struct variable_list *);
extern void send_isisSequenceNumberSkip_v2trap(struct variable_list *);
extern void send_isisAuthenticationTypeFailure_v2trap(struct variable_list *);
extern void send_isisAuthenticationFailure_v2trap(struct variable_list *);
extern void send_isisVersionSkew_v2trap(struct variable_list *);
extern void send_isisAreaMismatch_v2trap(struct variable_list *);
extern void send_isisRejectedAdjacency_v2trap(struct variable_list *);
extern void send_isisLSPTooLargeToPropagate_v2trap(struct variable_list *);
extern void send_isisOrigLSPBuffSizeMismatch_v2trap(struct variable_list *);
extern void send_isisProtocolsSupportedMismatch_v2trap(struct variable_list *);
extern void send_isisAdjacencyChange_v2trap(struct variable_list *);
extern void send_isisLSPErrorDetected_v2trap(struct variable_list *);

/* variable function prototypes */
void init_isisMIB(void);
void deinit_isisMIB(void);
int term_isisMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_isisMIB;
struct isisMIB_data *isisMIB_create(void);
struct isisMIB_data *isisMIB_duplicate(struct isisMIB_data *);
int isisMIB_destroy(struct isisMIB_data **);
int isisMIB_add(struct isisMIB_data *);
void parse_isisMIB(const char *, char *);
SNMPCallback store_isisMIB;
void refresh_isisMIB(int);
FindVarMethod var_isisManAreaAddrTable;
struct isisManAreaAddrTable_data *isisManAreaAddrTable_create(void);
struct isisManAreaAddrTable_data *isisManAreaAddrTable_duplicate(struct isisManAreaAddrTable_data *);
int isisManAreaAddrTable_destroy(struct isisManAreaAddrTable_data **);
int isisManAreaAddrTable_add(struct isisManAreaAddrTable_data *);
int isisManAreaAddrTable_del(struct isisManAreaAddrTable_data *);
void parse_isisManAreaAddrTable(const char *, char *);
SNMPCallback store_isisManAreaAddrTable;
void refresh_isisManAreaAddrTable(int);
FindVarMethod var_isisAreaAddrTable;
struct isisAreaAddrTable_data *isisAreaAddrTable_create(void);
struct isisAreaAddrTable_data *isisAreaAddrTable_duplicate(struct isisAreaAddrTable_data *);
int isisAreaAddrTable_destroy(struct isisAreaAddrTable_data **);
int isisAreaAddrTable_add(struct isisAreaAddrTable_data *);
int isisAreaAddrTable_del(struct isisAreaAddrTable_data *);
void parse_isisAreaAddrTable(const char *, char *);
SNMPCallback store_isisAreaAddrTable;
void refresh_isisAreaAddrTable(int);
FindVarMethod var_isisSummAddrTable;
struct isisSummAddrTable_data *isisSummAddrTable_create(void);
struct isisSummAddrTable_data *isisSummAddrTable_duplicate(struct isisSummAddrTable_data *);
int isisSummAddrTable_destroy(struct isisSummAddrTable_data **);
int isisSummAddrTable_add(struct isisSummAddrTable_data *);
int isisSummAddrTable_del(struct isisSummAddrTable_data *);
void parse_isisSummAddrTable(const char *, char *);
SNMPCallback store_isisSummAddrTable;
void refresh_isisSummAddrTable(int);
FindVarMethod var_isisRedistributeAddrTable;
struct isisRedistributeAddrTable_data *isisRedistributeAddrTable_create(void);
struct isisRedistributeAddrTable_data *isisRedistributeAddrTable_duplicate(struct isisRedistributeAddrTable_data *);
int isisRedistributeAddrTable_destroy(struct isisRedistributeAddrTable_data **);
int isisRedistributeAddrTable_add(struct isisRedistributeAddrTable_data *);
int isisRedistributeAddrTable_del(struct isisRedistributeAddrTable_data *);
void parse_isisRedistributeAddrTable(const char *, char *);
SNMPCallback store_isisRedistributeAddrTable;
void refresh_isisRedistributeAddrTable(int);
FindVarMethod var_isisRouterTable;
struct isisRouterTable_data *isisRouterTable_create(void);
struct isisRouterTable_data *isisRouterTable_duplicate(struct isisRouterTable_data *);
int isisRouterTable_destroy(struct isisRouterTable_data **);
int isisRouterTable_add(struct isisRouterTable_data *);
int isisRouterTable_del(struct isisRouterTable_data *);
void parse_isisRouterTable(const char *, char *);
SNMPCallback store_isisRouterTable;
void refresh_isisRouterTable(int);
FindVarMethod var_isisSysLevelTable;
struct isisSysLevelTable_data *isisSysLevelTable_create(void);
struct isisSysLevelTable_data *isisSysLevelTable_duplicate(struct isisSysLevelTable_data *);
int isisSysLevelTable_destroy(struct isisSysLevelTable_data **);
int isisSysLevelTable_add(struct isisSysLevelTable_data *);
int isisSysLevelTable_del(struct isisSysLevelTable_data *);
void parse_isisSysLevelTable(const char *, char *);
SNMPCallback store_isisSysLevelTable;
void refresh_isisSysLevelTable(int);
FindVarMethod var_isisCircTable;
struct isisCircTable_data *isisCircTable_create(void);
struct isisCircTable_data *isisCircTable_duplicate(struct isisCircTable_data *);
int isisCircTable_destroy(struct isisCircTable_data **);
int isisCircTable_add(struct isisCircTable_data *);
int isisCircTable_del(struct isisCircTable_data *);
void parse_isisCircTable(const char *, char *);
SNMPCallback store_isisCircTable;
void refresh_isisCircTable(int);
FindVarMethod var_isisCircLevelTable;
struct isisCircLevelTable_data *isisCircLevelTable_create(void);
struct isisCircLevelTable_data *isisCircLevelTable_duplicate(struct isisCircLevelTable_data *);
int isisCircLevelTable_destroy(struct isisCircLevelTable_data **);
int isisCircLevelTable_add(struct isisCircLevelTable_data *);
int isisCircLevelTable_del(struct isisCircLevelTable_data *);
void parse_isisCircLevelTable(const char *, char *);
SNMPCallback store_isisCircLevelTable;
void refresh_isisCircLevelTable(int);
FindVarMethod var_isisSystemCounterTable;
struct isisSystemCounterTable_data *isisSystemCounterTable_create(void);
struct isisSystemCounterTable_data *isisSystemCounterTable_duplicate(struct isisSystemCounterTable_data *);
int isisSystemCounterTable_destroy(struct isisSystemCounterTable_data **);
int isisSystemCounterTable_add(struct isisSystemCounterTable_data *);
int isisSystemCounterTable_del(struct isisSystemCounterTable_data *);
void parse_isisSystemCounterTable(const char *, char *);
SNMPCallback store_isisSystemCounterTable;
void refresh_isisSystemCounterTable(int);
FindVarMethod var_isisCircuitCounterTable;
struct isisCircuitCounterTable_data *isisCircuitCounterTable_create(void);
struct isisCircuitCounterTable_data *isisCircuitCounterTable_duplicate(struct isisCircuitCounterTable_data *);
int isisCircuitCounterTable_destroy(struct isisCircuitCounterTable_data **);
int isisCircuitCounterTable_add(struct isisCircuitCounterTable_data *);
int isisCircuitCounterTable_del(struct isisCircuitCounterTable_data *);
void parse_isisCircuitCounterTable(const char *, char *);
SNMPCallback store_isisCircuitCounterTable;
void refresh_isisCircuitCounterTable(int);
FindVarMethod var_isisPacketCounterTable;
struct isisPacketCounterTable_data *isisPacketCounterTable_create(void);
struct isisPacketCounterTable_data *isisPacketCounterTable_duplicate(struct isisPacketCounterTable_data *);
int isisPacketCounterTable_destroy(struct isisPacketCounterTable_data **);
int isisPacketCounterTable_add(struct isisPacketCounterTable_data *);
int isisPacketCounterTable_del(struct isisPacketCounterTable_data *);
void parse_isisPacketCounterTable(const char *, char *);
SNMPCallback store_isisPacketCounterTable;
void refresh_isisPacketCounterTable(int);
FindVarMethod var_isisISAdjTable;
struct isisISAdjTable_data *isisISAdjTable_create(void);
struct isisISAdjTable_data *isisISAdjTable_duplicate(struct isisISAdjTable_data *);
int isisISAdjTable_destroy(struct isisISAdjTable_data **);
int isisISAdjTable_add(struct isisISAdjTable_data *);
int isisISAdjTable_del(struct isisISAdjTable_data *);
void parse_isisISAdjTable(const char *, char *);
SNMPCallback store_isisISAdjTable;
void refresh_isisISAdjTable(int);
FindVarMethod var_isisISAdjAreaAddrTable;
struct isisISAdjAreaAddrTable_data *isisISAdjAreaAddrTable_create(void);
struct isisISAdjAreaAddrTable_data *isisISAdjAreaAddrTable_duplicate(struct isisISAdjAreaAddrTable_data *);
int isisISAdjAreaAddrTable_destroy(struct isisISAdjAreaAddrTable_data **);
int isisISAdjAreaAddrTable_add(struct isisISAdjAreaAddrTable_data *);
int isisISAdjAreaAddrTable_del(struct isisISAdjAreaAddrTable_data *);
void parse_isisISAdjAreaAddrTable(const char *, char *);
SNMPCallback store_isisISAdjAreaAddrTable;
void refresh_isisISAdjAreaAddrTable(int);
FindVarMethod var_isisISAdjIPAddrTable;
struct isisISAdjIPAddrTable_data *isisISAdjIPAddrTable_create(void);
struct isisISAdjIPAddrTable_data *isisISAdjIPAddrTable_duplicate(struct isisISAdjIPAddrTable_data *);
int isisISAdjIPAddrTable_destroy(struct isisISAdjIPAddrTable_data **);
int isisISAdjIPAddrTable_add(struct isisISAdjIPAddrTable_data *);
int isisISAdjIPAddrTable_del(struct isisISAdjIPAddrTable_data *);
void parse_isisISAdjIPAddrTable(const char *, char *);
SNMPCallback store_isisISAdjIPAddrTable;
void refresh_isisISAdjIPAddrTable(int);
FindVarMethod var_isisISAdjProtSuppTable;
struct isisISAdjProtSuppTable_data *isisISAdjProtSuppTable_create(void);
struct isisISAdjProtSuppTable_data *isisISAdjProtSuppTable_duplicate(struct isisISAdjProtSuppTable_data *);
int isisISAdjProtSuppTable_destroy(struct isisISAdjProtSuppTable_data **);
int isisISAdjProtSuppTable_add(struct isisISAdjProtSuppTable_data *);
int isisISAdjProtSuppTable_del(struct isisISAdjProtSuppTable_data *);
void parse_isisISAdjProtSuppTable(const char *, char *);
SNMPCallback store_isisISAdjProtSuppTable;
void refresh_isisISAdjProtSuppTable(int);
FindVarMethod var_isisRATable;
struct isisRATable_data *isisRATable_create(void);
struct isisRATable_data *isisRATable_duplicate(struct isisRATable_data *);
int isisRATable_destroy(struct isisRATable_data **);
int isisRATable_add(struct isisRATable_data *);
int isisRATable_del(struct isisRATable_data *);
void parse_isisRATable(const char *, char *);
SNMPCallback store_isisRATable;
void refresh_isisRATable(int);
FindVarMethod var_isisIPRATable;
struct isisIPRATable_data *isisIPRATable_create(void);
struct isisIPRATable_data *isisIPRATable_duplicate(struct isisIPRATable_data *);
int isisIPRATable_destroy(struct isisIPRATable_data **);
int isisIPRATable_add(struct isisIPRATable_data *);
int isisIPRATable_del(struct isisIPRATable_data *);
void parse_isisIPRATable(const char *, char *);
SNMPCallback store_isisIPRATable;
void refresh_isisIPRATable(int);
FindVarMethod var_isisLSPSummaryTable;
struct isisLSPSummaryTable_data *isisLSPSummaryTable_create(void);
struct isisLSPSummaryTable_data *isisLSPSummaryTable_duplicate(struct isisLSPSummaryTable_data *);
int isisLSPSummaryTable_destroy(struct isisLSPSummaryTable_data **);
int isisLSPSummaryTable_add(struct isisLSPSummaryTable_data *);
int isisLSPSummaryTable_del(struct isisLSPSummaryTable_data *);
void parse_isisLSPSummaryTable(const char *, char *);
SNMPCallback store_isisLSPSummaryTable;
void refresh_isisLSPSummaryTable(int);
FindVarMethod var_isisLSPTLVTable;
struct isisLSPTLVTable_data *isisLSPTLVTable_create(void);
struct isisLSPTLVTable_data *isisLSPTLVTable_duplicate(struct isisLSPTLVTable_data *);
int isisLSPTLVTable_destroy(struct isisLSPTLVTable_data **);
int isisLSPTLVTable_add(struct isisLSPTLVTable_data *);
int isisLSPTLVTable_del(struct isisLSPTLVTable_data *);
void parse_isisLSPTLVTable(const char *, char *);
SNMPCallback store_isisLSPTLVTable;
void refresh_isisLSPTLVTable(int);

WriteMethod write_isisSysLevelType;
WriteMethod write_isisSysID;
WriteMethod write_isisSysMaxPathSplits;
WriteMethod write_isisSysMaxLSPGenInt;
WriteMethod write_isisSysPollESHelloRate;
WriteMethod write_isisSysWaitTime;
WriteMethod write_isisSysAdminState;
WriteMethod write_isisSysL2toL1Leaking;
WriteMethod write_isisSysMaxAge;
WriteMethod write_isisSysReceiveLSPBufferSize;
WriteMethod write_isisSysNotificationEnable;
WriteMethod write_isisManAreaAddrExistState;
WriteMethod write_isisSummAddrExistState;
WriteMethod write_isisSummAddrMetric;
WriteMethod write_isisSummAddrFullMetric;
WriteMethod write_isisRedistributeAddrExistState;
WriteMethod write_isisSysLevelOrigLSPBuffSize;
WriteMethod write_isisSysLevelMinLSPGenInt;
WriteMethod write_isisSysLevelSetOverload;
WriteMethod write_isisSysLevelSetOverloadUntil;
WriteMethod write_isisSysLevelMetricStyle;
WriteMethod write_isisSysLevelSPFConsiders;
WriteMethod write_isisSysLevelTEEnabled;
WriteMethod write_isisCircIfIndex;
WriteMethod write_isisCircAdminState;
WriteMethod write_isisCircExistState;
WriteMethod write_isisCircType;
WriteMethod write_isisCircExtDomain;
WriteMethod write_isisCircLevelType;
WriteMethod write_isisCircPassiveCircuit;
WriteMethod write_isisCircMeshGroupEnabled;
WriteMethod write_isisCircMeshGroup;
WriteMethod write_isisCircSmallHellos;
WriteMethod write_isisCirc3WayEnabled;
WriteMethod write_isisCircExtendedCircID;
WriteMethod write_isisCircLevelMetric;
WriteMethod write_isisCircLevelWideMetric;
WriteMethod write_isisCircLevelISPriority;
WriteMethod write_isisCircLevelHelloMultiplier;
WriteMethod write_isisCircLevelHelloTimer;
WriteMethod write_isisCircLevelDRHelloTimer;
WriteMethod write_isisCircLevelLSPThrottle;
WriteMethod write_isisCircLevelMinLSPRetransInt;
WriteMethod write_isisCircLevelCSNPInterval;
WriteMethod write_isisCircLevelPartSNPInterval;
WriteMethod write_isisRAExistState;
WriteMethod write_isisRAAdminState;
WriteMethod write_isisRAAddrPrefix;
WriteMethod write_isisRAMapType;
WriteMethod write_isisRAMetric;
WriteMethod write_isisRAMetricType;
WriteMethod write_isisRASNPAAddress;
WriteMethod write_isisRASNPAMask;
WriteMethod write_isisRASNPAPrefix;
WriteMethod write_isisRAType;
WriteMethod write_isisIPRANextHopType;
WriteMethod write_isisIPRANextHop;
WriteMethod write_isisIPRAType;
WriteMethod write_isisIPRAExistState;
WriteMethod write_isisIPRAAdminState;
WriteMethod write_isisIPRAMetric;
WriteMethod write_isisIPRAMetricType;
WriteMethod write_isisIPRAFullMetric;
WriteMethod write_isisIPRASNPAAddress;
#endif				/* __LOCAL_ISISMIB_H__ */
