/*****************************************************************************

 @(#) src/snmp/lldpv2tcmib.c

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2015  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, version 3 of the license.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 *****************************************************************************/

static char const ident[] = "src/snmp/lldpv2tcmib.c (" PACKAGE_ENVR ") " PACKAGE_DATE;

/* This file was generated by mib2c and is intended for use as
   a mib module for the ucd-snmp snmpd agent. */
#include <ucd-snmp/ucd-snmp-config.h>
#include <ucd-snmp/ucd-snmp-includes.h>
#include <ucd-snmp/ucd-snmp-agent-includes.h>
#include <ucd-snmp/agent_trap.h>
#include <ucd-snmp/callback.h>
#include <ucd-snmp/snmp-tc.h>
#include <ucd-snmp/default_store.h>
#include <ucd-snmp/snmp_alarm.h>
/* The following header files are mangled in most recent net-snmp releases so
 * the versions from UCD-SNMP 4.2.5 are included here.  */
#if defined HAVE_LIBNETSNMP
#else				/* defined HAVE_LIBNETSNMP */
#endif				/* defined HAVE_LIBNETSNMP */
/* These are messed up on both. */
#include "ds_agent.h"
#ifdef HAVE_UCD_SNMP_UTIL_FUNCS_H
#include <ucd-snmp/util_funcs.h>
/* Many recent net-snmp UCD compatible headers do not declare header_generic. */
int header_generic(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
#else				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#include "util_funcs.h"
#endif				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#ifdef HAVE_UCD_SNMP_HEADER_COMPLEX_H
#include <ucd-snmp/header_complex.h>
#else				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
#include "header_complex.h"
#endif				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
/* This one is the other way around: it is just fine for net-snmp, but
 * ucd-snmp does not provide the header file at all.  */
#ifdef HAVE_UCD_SNMP_MIB_MODULES_H
#include <ucd-snmp/mib_modules.h>
#else				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#ifdef HAVE_NET_SNMP_AGENT_MIB_MODULES_H
#include <net-snmp/agent/mib_modules.h>
#else				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#include "mib_modules.h"
#endif				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#endif				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#include <stdint.h>
#include <signal.h>
#include <sys/stat.h>		/* for struct stat, fstat() */
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <pwd.h>		/* for getpwuid() getpwnam() */
#include <grp.h>		/* for getgrgid() getgrnam() */
#include <libgen.h>		/* for basename() */
#include <fcntl.h>		/* for O_CREAT */
#include <sys/sysctl.h>		/* for sysctl */
#include <errno.h>
#include <string.h>
#ifdef _GNU_SOURCE
#include <getopt.h>
#endif
#include "lldpV2TcMIB.h"
#define MASTER 1
#define MY_FACILITY(__pri)	(LOG_DAEMON|(__pri))
#if defined MODULE
#if defined MASTER
const char sa_program[] = "lldpV2TcMIB";
int sa_fclose = 1;			/* default close files between requests */
int sa_changed = 1;			/* indication to reread MIB configuration */
int sa_stats_refresh = 1;		/* indications that statistics, the mib or its tables need to be refreshed */
int sa_request = 1;			/* request number for per-request actions */
int sa_dump = 0;			/* default packet dump */
int sa_debug = 0;			/* default no debug */
#endif				/* defined MASTER */
#endif				/* defined MODULE */
static int my_fd = -1;			/* file descriptor for this MIB's use */
static int my_readfd = -1;		/* file descriptor for autonomnous events */
volatile int lldpV2TcMIB_refresh = 1;

/*
 * lldpV2TcMIB_variables_oid: object identifier for lldpV2TcMIB
 * This is the top level oid that we want to register under.  This is essentially a prefix, with the
 * suffix appearing in the variable below.
 */
oid lldpV2TcMIB_variables_oid[8] = { 1, 3, 111, 2, 802, 1, 1, 12 };

/*
 * Oids for use in notifications defined in this MIB.
 */

/*
 * Oids accessible only for notify defined in this MIB.
 */

/*
 * Other oids defined in this MIB.
 */

static oid zeroDotZero_oid[2] = { 0, 0 };
static oid snmpTrapOID_oid[11] = { 1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0 };

/*
 * variable2 lldpV2TcMIB_variables: tree for lldpV2TcMIB
 * This variable defines function callbacks and type return information for the lldpV2TcMIB mib section
 */
struct variable2 lldpV2TcMIB_variables[] = {
	/* magic number, variable type, ro/rw, callback fn, L, oidsuffix */

};

/* (L = length of the oidsuffix) */
struct lldpV2TcMIB_data *lldpV2TcMIBStorage = NULL;

/* global storage of our data, saved in and configured by header_complex() */

void (*lldpV2TcMIBold_signal_handler) (int) = NULL;	/* save old signal handler just in case */
void lldpV2TcMIB_loop_handler(int);
void lldpV2TcMIB_fd_handler(int, void *);

/**
 * @fn void init_lldpV2TcMIB(void)
 * @brief lldpV2TcMIB initialization routine.
 *
 * This is called when the agent starts up.  At a minimum, registration of the MIB variables
 * structure (lldpV2TcMIB_variables) should take place here.  By default the function also
 * registers the configuration handler and configuration store callbacks.
 *
 * Additional registrations that may be considered here are calls to regsiter_readfd(),
 * register_writefd() and register_exceptfd() for hooking into the snmpd event loop, but only when
 * used as a loadable module.  By default this function establishes a single file descriptor to
 * read, or upon which to handle exceptions.  Note that the snmpd only supports a maximum of 32
 * extneral file descriptors, so these should be used sparingly.
 *
 * When running as a loadable module, it is also necessary to hook into the snmpd event loop so that
 * the current request number can be deteremined.  This is accomplished by using a trick of the
 * external_signal_scheduled and external_signal_handler mechanism which is called on each event
 * loop when external_signal_scheduled is non-zero.  This is used to increment the sa_request value
 * on each snmpd event loop interation so that calls to MIB tree functions can determine whether
 * they belong to a fresh request or not (primarily for cacheing and possibly to clean up non-polled
 * file descriptors).
 */
void
init_lldpV2TcMIB(void)
{
	(void) my_fd;
	(void) zeroDotZero_oid;
	(void) snmpTrapOID_oid;
	DEBUGMSGTL(("lldpV2TcMIB", "init_lldpV2TcMIB: initializing...  "));
	/* register ourselves with the agent to handle our mib tree */
	REGISTER_MIB("lldpV2TcMIB", lldpV2TcMIB_variables, variable2, lldpV2TcMIB_variables_oid);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_SHUTDOWN, term_lldpV2TcMIB, NULL);
	/* register our config handler(s) to deal with registrations */
	snmpd_register_config_handler("lldpV2TcMIB", parse_lldpV2TcMIB, NULL, "HELP STRING");
	/* we need to be called back later to store our data */
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_lldpV2TcMIB, NULL);
	/* place any other initialization junk you need here */
	if (my_readfd >= 0) {
		register_readfd(my_readfd, lldpV2TcMIB_fd_handler, (void *) 0);
		register_exceptfd(my_readfd, lldpV2TcMIB_fd_handler, (void *) 1);
	}
	lldpV2TcMIBold_signal_handler = external_signal_handler[SIGCHLD];
	external_signal_handler[SIGCHLD] = &lldpV2TcMIB_loop_handler;
	external_signal_scheduled[SIGCHLD] = 1;
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
}

/**
 * @fn void deinit_lldpV2TcMIB(void)
 * @brief deinitialization routine.
 *
 * This is called before the agent is unloaded.  At a minimum, deregistration of the MIB variables
 * structure (lldpV2TcMIB_variables) should take place here.  By default, the function also
 * deregisters the the configuration file handlers for the MIB variables and table rows.
 *
 * Additional deregistrations that may be required here are calls to unregister_readfd(),
 * unregister_writefd() and unregsiter_exceptfd() for unhooking from the snmpd event loop, but only
 * when used as a loadable module.  By default if a read file descriptor exists, it is unregistered.
 */
void
deinit_lldpV2TcMIB(void)
{
	DEBUGMSGTL(("lldpV2TcMIB", "deinit_lldpV2TcMIB: deinitializating...  "));
	external_signal_handler[SIGCHLD] = lldpV2TcMIBold_signal_handler;
	if (my_readfd >= 0) {
		unregister_exceptfd(my_readfd);
		unregister_readfd(my_readfd);
		close(my_readfd);
		my_readfd = -1;
	}
	unregister_mib(lldpV2TcMIB_variables_oid, sizeof(lldpV2TcMIB_variables_oid) / sizeof(oid));
	snmpd_unregister_config_handler("lldpV2TcMIB");
	/* place any other de-initialization junk you need here */
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
}

int
term_lldpV2TcMIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	DEBUGMSGTL(("lldpV2TcMIB", "term_lldpV2TcMIB: terminating...  "));
	deinit_lldpV2TcMIB();
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
	return 0;
}

/**
 * @fn struct lldpV2TcMIB_data *lldpV2TcMIB_create(void)
 * @brief create a fresh data structure representing scalars in lldpV2TcMIB.
 *
 * Creates a new lldpV2TcMIB_data structure by allocating dynamic memory for the structure and
 * initializing the default values of scalars in lldpV2TcMIB.
 */
struct lldpV2TcMIB_data *
lldpV2TcMIB_create(void)
{
	struct lldpV2TcMIB_data *StorageNew = SNMP_MALLOC_STRUCT(lldpV2TcMIB_data);

	DEBUGMSGTL(("lldpV2TcMIB", "lldpV2TcMIB_create: creating scalars...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default scalar values here into StorageNew */

	}
      done:
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	lldpV2TcMIB_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct lldpV2TcMIB_data *lldpV2TcMIB_duplicate(struct lldpV2TcMIB_data *thedata)
 * @param thedata the mib structure to duplicate
 * @brief duplicate a mib structure for the mib
 *
 * Duplicates the specified mib structure @param thedata and returns a pointer to the newly
 * allocated mib structure on success, or NULL on failure.
 */
struct lldpV2TcMIB_data *
lldpV2TcMIB_duplicate(struct lldpV2TcMIB_data *thedata)
{
	struct lldpV2TcMIB_data *StorageNew = SNMP_MALLOC_STRUCT(lldpV2TcMIB_data);

	DEBUGMSGTL(("lldpV2TcMIB", "lldpV2TcMIB_duplicate: duplicating mib... "));
	if (StorageNew != NULL) {
	}
      done:
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	lldpV2TcMIB_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int lldpV2TcMIB_destroy(struct lldpV2TcMIB_data **thedata)
 * @param thedata pointer to the data structure in lldpV2TcMIB.
 * @brief delete a scalars structure from lldpV2TcMIB.
 *
 * Frees scalars that were previously removed from lldpV2TcMIB.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
lldpV2TcMIB_destroy(struct lldpV2TcMIB_data **thedata)
{
	struct lldpV2TcMIB_data *StorageDel;

	DEBUGMSGTL(("lldpV2TcMIB", "lldpV2TcMIB_destroy: deleting scalars...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int lldpV2TcMIB_add(struct lldpV2TcMIB_data *thedata)
 * @param thedata the structure representing lldpV2TcMIB scalars.
 * @brief adds node to the lldpV2TcMIB scalar data set.
 *
 * Adds a scalar structure to the lldpV2TcMIB data set.  Note that this function is necessary even
 * when the scalar values are not peristent.
 */
int
lldpV2TcMIB_add(struct lldpV2TcMIB_data *thedata)
{
	DEBUGMSGTL(("lldpV2TcMIB", "lldpV2TcMIB_add: adding data...  "));
	if (thedata)
		lldpV2TcMIBStorage = thedata;
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_lldpV2TcMIB(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for lldpV2TcMIB entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case lldpV2TcMIB).  This routine is invoked by
 * UCD-SNMP to read the values of scalars in the MIB from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the MIB.  If there are no configured entries
 * in the configuration MIB, this function will simply not be called.
 */
void
parse_lldpV2TcMIB(const char *token, char *line)
{
	size_t tmpsize;
	struct lldpV2TcMIB_data *StorageTmp = lldpV2TcMIB_create();

	DEBUGMSGTL(("lldpV2TcMIB", "parse_lldpV2TcMIB: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual scalars that are not persistent */
	lldpV2TcMIB_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
}

/*
 * store_lldpV2TcMIB(): stores .conf file entries needed to configure the mib.
 */
int
store_lldpV2TcMIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct lldpV2TcMIB_data *StorageTmp;

	DEBUGMSGTL(("lldpV2TcMIB", "store_lldpV2TcMIB: storing data...  "));
	refresh_lldpV2TcMIB(1);
	if ((StorageTmp = lldpV2TcMIBStorage) == NULL) {
		DEBUGMSGTL(("lldpV2TcMIB", "error.\n"));
		return SNMPERR_GENERR;
	}
	(void) tmpsize;
	/* XXX: comment entire section if no scalars are persistent */
	{
		memset(line, 0, sizeof(line));
		strcat(line, "lldpV2TcMIB ");
		cptr = line + strlen(line);
		(void) cptr;
		/* XXX: remove individual scalars that are not persistent */
		snmpd_store_config(line);
	}
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int check_lldpV2TcMIB(struct lldpV2TcMIB_data *StorageTmp, struct lldpV2TcMIB_data *StorageOld)
 * @param StorageTmp the data as updated
 * @param StorageOld the data previous to update
 *
 * This function is used by mibs.  It is used to check, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the ACTION phase.  The COMMIT phase does not ensue unless this check passes.  This function can
 * return SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before
 * the varbinds on the mib were applied; the values in StorageTmp are the new values.  The function
 * is permitted to change the values in StorageTmp to correct them; however, preferences should be
 * made for setting values that were not in the varbinds.
 */
int
check_lldpV2TcMIB(struct lldpV2TcMIB_data *StorageTmp, struct lldpV2TcMIB_data *StorageOld)
{
	/* XXX: provide code to check the scalars for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_lldpV2TcMIB(struct lldpV2TcMIB_data *StorageTmp, struct lldpV2TcMIB_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase)
 *
 * This function is used by mibs.  It is used to update, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the COMMIT phase.  The start of the ACTION phase performs a consistency check on the mib before
 * allowing the request to proceed to the COMMIT phase.  The COMMIT phase then arrives here with
 * consistency already checked (see check_lldpV2TcMIB()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the mib were applied: the values in StorageTmp are the new values.
 */
int
update_lldpV2TcMIB(struct lldpV2TcMIB_data *StorageTmp, struct lldpV2TcMIB_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	lldpV2TcMIB_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn revert_lldpV2TcMIB(struct 
 * @fn void revert_lldpV2TcMIB(struct lldpV2TcMIB_data *StorageTmp, struct lldpV2TcMIB_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase)
 */
void
revert_lldpV2TcMIB(struct lldpV2TcMIB_data *StorageTmp, struct lldpV2TcMIB_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_lldpV2TcMIB(StorageOld, NULL);
}

/**
 * @fn void refresh_lldpV2TcMIB(int force)
 * @param force forced refresh when non-zero.
 * @brief refresh the scalar values of lldpV2TcMIB.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a scalar has been requested).
 */
void
refresh_lldpV2TcMIB(int force)
{
	if (lldpV2TcMIBStorage == NULL) {
		struct lldpV2TcMIB_data *StorageNew;

		if ((StorageNew = lldpV2TcMIB_create()) == NULL)
			return;
		lldpV2TcMIBStorage = StorageNew;
		lldpV2TcMIB_refresh = 1;
	}
	if (!force && lldpV2TcMIB_refresh == 0)
		return;
	DEBUGMSGTL(("lldpV2TcMIB", "refresh_lldpV2TcMIB: refreshing...  "));
	/* XXX: Update scalars as required here... */
	lldpV2TcMIB_refresh = 0;
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
}

/**
 * @fn u_char * var_lldpV2TcMIB(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @param vp a pointer to the entry in the variables table for the requested variable.
 * @param name the object identifier for which to find.
 * @param length the length of the object identifier.
 * @param exact whether the name is exact.
 * @param var_len a pointer to the length of the representation of the object.
 * @param write_method a pointer to a write method for the object.
 * @brief locate variables in lldpV2TcMIB.
 *
 * This function returns a pointer to a memory area that is static across the request that contains
 * the UCD-SNMP representation of the scalar (so that it may be used to read from for a GET,
 * GET-NEXT or GET-BULK request).  This returned pointer may be NULL, in which case the function is
 * telling UCD-SNMP that the scalar does not exist for reading; however, if write_method is
 * overwritten with a non-NULL value, the function is telling UCD-SNMP that the scalar exists for
 * writing.  Write-only objects can be effected in this way.
 */
u_char *
var_lldpV2TcMIB(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct lldpV2TcMIB_data *StorageTmp;
	u_char *rval;

	DEBUGMSGTL(("lldpV2TcMIB", "var_lldpV2TcMIB: lookup up varbind...  "));
	if (header_generic(vp, name, length, exact, var_len, write_method) == MATCH_FAILED)
		return NULL;
	/* Refresh the MIB values if required. */
	refresh_lldpV2TcMIB(0);
	if ((StorageTmp = lldpV2TcMIBStorage) == NULL) {
		DEBUGMSGTL(("lldpV2TcMIB", "no datastructure.\n"));
		return NULL;
	}
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	default:
		ERROR_MSG("");
	}
	if (rval)
		DEBUGMSGTL(("lldpV2TcMIB", "found.\n"));
	else
		DEBUGMSGTL(("lldpV2TcMIB", "not found.\n"));
	return (rval);
}

/**
 * @fn void lldpV2TcMIB_loop_handler(int dummy)
 * @param sig signal number
 * @brief handle event loop interation.
 *
 * This function is registered so that, when operating as a module, snmpd will call it one per event
 * loop interation.  This function is called before the next requst is processed and after the
 * previous request is processed.  Two things are done here:  1) The file descriptor that is used to
 * synchronize the agent with (pseudo-)device drivers is closed.  (Another approach, instead of
 * closing each time, would be to restart a timer each time that a request is made (loop is
 * performed) and if it expires, close the file descriptor).  2) The request number is incremented.
 * Although a request is not generated for each loop of the snmp event loop, it is true that a new
 * request cannot be generated without performing a loop.  Therefore, the sa_request is not the
 * request number but it is a temporally unique identifier for a request.
 */
void
lldpV2TcMIB_loop_handler(int sig)
{
	DEBUGMSGTL(("lldpV2TcMIB", "lldpV2TcMIB_loop_handler: executing loop handler...  "));
	/* close files after each request */
	if (sa_fclose) {
		if (my_fd >= 0) {
			close(my_fd);
			my_fd = -1;
		}
	}
#if defined MASTER
	/* prepare for next request */
	sa_request++;
#endif				/* defined MASTER */
	if (external_signal_scheduled[sig] == 0)
		external_signal_scheduled[sig]--;
	if (lldpV2TcMIBold_signal_handler != NULL)
		(*lldpV2TcMIBold_signal_handler) (sig);
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
}

/**
 * @fn void lldpV2TcMIB_fd_handler(int fd, void *dummy)
 * @param fd file descriptor to read.
 * @param dummy client data passed to registration function (always NULL).
 * @brief handle read event on file descriptor.
 *
 * This read file descriptor handler is normally used for (pseudo-)device drivers that generate
 * statistical collection interval events, alarm events, or other operational measurement events, by
 * placing a message on the read queue of the "event handling" Stream.  Normally this routine
 * would adjust counts in some table or scalars, generate SNMP traps representing on-occurence
 * events, first and interval events, and alarm indications.
 */
void
lldpV2TcMIB_fd_handler(int fd, void *dummy)
{
	DEBUGMSGTL(("lldpV2TcMIB", "lldpV2TcMIB_fd_handler: executing fd handler...  "));
	/* XXX: place actions to handle my_fd here... */
	DEBUGMSGTL(("lldpV2TcMIB", "done.\n"));
	return;
}
