/*****************************************************************************

 @(#) src/snmp/lldpv2mib.h

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2015  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 *****************************************************************************/

#ifndef __LOCAL_LLDPV2MIB_H__
#define __LOCAL_LLDPV2MIB_H__

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct lldpV2MIB_data {
	struct lldpV2MIB_data *lldpV2MIB_old;
	uint lldpV2MIB_rsvs;
	uint lldpV2MIB_tsts;
	uint lldpV2MIB_sets;
	uint lldpV2MIB_request;
	ulong lldpV2MessageTxInterval;	/* ReadWrite */
	ulong lldpV2MessageTxHoldMultiplier;	/* ReadWrite */
	ulong lldpV2ReinitDelay;	/* ReadWrite */
	ulong lldpV2NotificationInterval;	/* ReadWrite */
	ulong lldpV2TxCreditMax;	/* ReadWrite */
	ulong lldpV2MessageFastTx;	/* ReadWrite */
	ulong lldpV2TxFastInit;		/* ReadWrite */
	long lldpV2StatsRemTablesLastChangeTime;	/* ReadOnly */
	long lldpV2StatsRemTablesInserts;	/* ReadOnly */
	long lldpV2StatsRemTablesDeletes;	/* ReadOnly */
	long lldpV2StatsRemTablesDrops;	/* ReadOnly */
	long lldpV2StatsRemTablesAgeouts;	/* ReadOnly */
	long lldpV2LocChassisIdSubtype;	/* ReadOnly */
	uint8_t *lldpV2LocChassisId;	/* ReadOnly */
	size_t lldpV2LocChassisIdLen;
	uint8_t *lldpV2LocSysName;	/* ReadOnly */
	size_t lldpV2LocSysNameLen;
	uint8_t *lldpV2LocSysDesc;	/* ReadOnly */
	size_t lldpV2LocSysDescLen;
	uint8_t *lldpV2LocSysCapSupported;	/* ReadOnly */
	size_t lldpV2LocSysCapSupportedLen;
	uint8_t *lldpV2LocSysCapEnabled;	/* ReadOnly */
	size_t lldpV2LocSysCapEnabledLen;
};
struct lldpV2PortConfigTable_data {
	struct lldpV2PortConfigTable_data *lldpV2PortConfigTable_old;
	uint lldpV2PortConfigTable_rsvs;
	uint lldpV2PortConfigTable_tsts;
	uint lldpV2PortConfigTable_sets;
	uint lldpV2PortConfigTable_request;
	uint lldpV2PortConfigTable_refs;
	uint lldpV2PortConfigTable_id;
	long lldpV2PortConfigIfIndex;	/* NoAccess */
	ulong lldpV2PortConfigDestAddressIndex;	/* NoAccess */
	long lldpV2PortConfigAdminStatus;	/* ReadWrite */
	long lldpV2PortConfigNotificationEnable;	/* ReadWrite */
	uint8_t *lldpV2PortConfigTLVsTxEnable;	/* ReadWrite */
	size_t lldpV2PortConfigTLVsTxEnableLen;
};
struct lldpV2DestAddressTable_data {
	struct lldpV2DestAddressTable_data *lldpV2DestAddressTable_old;
	uint lldpV2DestAddressTable_rsvs;
	uint lldpV2DestAddressTable_tsts;
	uint lldpV2DestAddressTable_sets;
	uint lldpV2DestAddressTable_request;
	uint lldpV2DestAddressTable_refs;
	uint lldpV2DestAddressTable_id;
	ulong lldpV2AddressTableIndex;	/* NoAccess */
	uint8_t *lldpV2DestMacAddress;	/* ReadOnly */
	size_t lldpV2DestMacAddressLen;
};
struct lldpV2ManAddrConfigTxPortsTable_data {
	struct lldpV2ManAddrConfigTxPortsTable_data *lldpV2ManAddrConfigTxPortsTable_old;
	uint lldpV2ManAddrConfigTxPortsTable_rsvs;
	uint lldpV2ManAddrConfigTxPortsTable_tsts;
	uint lldpV2ManAddrConfigTxPortsTable_sets;
	uint lldpV2ManAddrConfigTxPortsTable_request;
	uint lldpV2ManAddrConfigTxPortsTable_refs;
	uint lldpV2ManAddrConfigTxPortsTable_id;
	long lldpV2ManAddrConfigIfIndex;	/* NoAccess */
	ulong lldpV2ManAddrConfigDestAddressIndex;	/* NoAccess */
	long lldpV2ManAddrConfigLocManAddrSubtype;	/* NoAccess */
	uint8_t *lldpV2ManAddrConfigLocManAddr;	/* NoAccess */
	size_t lldpV2ManAddrConfigLocManAddrLen;
	long lldpV2ManAddrConfigTxEnable;	/* Create */
	long lldpV2ManAddrConfigRowStatus;	/* Create */
};
struct lldpV2StatsTxPortTable_data {
	struct lldpV2StatsTxPortTable_data *lldpV2StatsTxPortTable_old;
	uint lldpV2StatsTxPortTable_rsvs;
	uint lldpV2StatsTxPortTable_tsts;
	uint lldpV2StatsTxPortTable_sets;
	uint lldpV2StatsTxPortTable_request;
	uint lldpV2StatsTxPortTable_refs;
	uint lldpV2StatsTxPortTable_id;
	long lldpV2StatsTxIfIndex;	/* NoAccess */
	ulong lldpV2StatsTxDestMACAddress;	/* NoAccess */
	long lldpV2StatsTxPortFramesTotal;	/* ReadOnly */
	long lldpV2StatsTxLLDPDULengthErrors;	/* ReadOnly */
};
struct lldpV2StatsRxPortTable_data {
	struct lldpV2StatsRxPortTable_data *lldpV2StatsRxPortTable_old;
	uint lldpV2StatsRxPortTable_rsvs;
	uint lldpV2StatsRxPortTable_tsts;
	uint lldpV2StatsRxPortTable_sets;
	uint lldpV2StatsRxPortTable_request;
	uint lldpV2StatsRxPortTable_refs;
	uint lldpV2StatsRxPortTable_id;
	long lldpV2StatsRxDestIfIndex;	/* NoAccess */
	ulong lldpV2StatsRxDestMACAddress;	/* NoAccess */
	long lldpV2StatsRxPortFramesDiscardedTotal;	/* ReadOnly */
	long lldpV2StatsRxPortFramesErrors;	/* ReadOnly */
	long lldpV2StatsRxPortFramesTotal;	/* ReadOnly */
	long lldpV2StatsRxPortTLVsDiscardedTotal;	/* ReadOnly */
	long lldpV2StatsRxPortTLVsUnrecognizedTotal;	/* ReadOnly */
	long lldpV2StatsRxPortAgeoutsTotal;	/* ReadOnly */
};
struct lldpV2LocPortTable_data {
	struct lldpV2LocPortTable_data *lldpV2LocPortTable_old;
	uint lldpV2LocPortTable_rsvs;
	uint lldpV2LocPortTable_tsts;
	uint lldpV2LocPortTable_sets;
	uint lldpV2LocPortTable_request;
	uint lldpV2LocPortTable_refs;
	uint lldpV2LocPortTable_id;
	long lldpV2LocPortIfIndex;	/* NoAccess */
	long lldpV2LocPortIdSubtype;	/* ReadOnly */
	uint8_t *lldpV2LocPortId;	/* ReadOnly */
	size_t lldpV2LocPortIdLen;
	uint8_t *lldpV2LocPortDesc;	/* ReadOnly */
	size_t lldpV2LocPortDescLen;
};
struct lldpV2LocManAddrTable_data {
	struct lldpV2LocManAddrTable_data *lldpV2LocManAddrTable_old;
	uint lldpV2LocManAddrTable_rsvs;
	uint lldpV2LocManAddrTable_tsts;
	uint lldpV2LocManAddrTable_sets;
	uint lldpV2LocManAddrTable_request;
	uint lldpV2LocManAddrTable_refs;
	uint lldpV2LocManAddrTable_id;
	long lldpV2LocManAddrSubtype;	/* NoAccess */
	uint8_t *lldpV2LocManAddr;	/* NoAccess */
	size_t lldpV2LocManAddrLen;
	ulong lldpV2LocManAddrLen;	/* ReadOnly */
	long lldpV2LocManAddrIfSubtype;	/* ReadOnly */
	ulong lldpV2LocManAddrIfId;	/* ReadOnly */
	oid *lldpV2LocManAddrOID;	/* ReadOnly */
	size_t lldpV2LocManAddrOIDLen;
};
struct lldpV2RemTable_data {
	struct lldpV2RemTable_data *lldpV2RemTable_old;
	uint lldpV2RemTable_rsvs;
	uint lldpV2RemTable_tsts;
	uint lldpV2RemTable_sets;
	uint lldpV2RemTable_request;
	uint lldpV2RemTable_refs;
	uint lldpV2RemTable_id;
	long lldpV2RemTimeMark;		/* NoAccess */
	long lldpV2RemLocalIfIndex;	/* NoAccess */
	ulong lldpV2RemLocalDestMACAddress;	/* NoAccess */
	ulong lldpV2RemIndex;		/* NoAccess */
	long lldpV2RemChassisIdSubtype;	/* ReadOnly */
	uint8_t *lldpV2RemChassisId;	/* ReadOnly */
	size_t lldpV2RemChassisIdLen;
	long lldpV2RemPortIdSubtype;	/* ReadOnly */
	uint8_t *lldpV2RemPortId;	/* ReadOnly */
	size_t lldpV2RemPortIdLen;
	uint8_t *lldpV2RemPortDesc;	/* ReadOnly */
	size_t lldpV2RemPortDescLen;
	uint8_t *lldpV2RemSysName;	/* ReadOnly */
	size_t lldpV2RemSysNameLen;
	uint8_t *lldpV2RemSysDesc;	/* ReadOnly */
	size_t lldpV2RemSysDescLen;
	uint8_t *lldpV2RemSysCapSupported;	/* ReadOnly */
	size_t lldpV2RemSysCapSupportedLen;
	uint8_t *lldpV2RemSysCapEnabled;	/* ReadOnly */
	size_t lldpV2RemSysCapEnabledLen;
	long lldpV2RemRemoteChanges;	/* ReadOnly */
	long lldpV2RemTooManyNeighbors;	/* ReadOnly */
};
struct lldpV2RemManAddrTable_data {
	struct lldpV2RemManAddrTable_data *lldpV2RemManAddrTable_old;
	uint lldpV2RemManAddrTable_rsvs;
	uint lldpV2RemManAddrTable_tsts;
	uint lldpV2RemManAddrTable_sets;
	uint lldpV2RemManAddrTable_request;
	uint lldpV2RemManAddrTable_refs;
	uint lldpV2RemManAddrTable_id;
	long lldpV2RemTimeMark;		/* NoAccess */
	long lldpV2RemLocalIfIndex;	/* NoAccess */
	ulong lldpV2RemLocalDestMACAddress;	/* NoAccess */
	ulong lldpV2RemIndex;		/* NoAccess */
	long lldpV2RemManAddrSubtype;	/* NoAccess */
	uint8_t *lldpV2RemManAddr;	/* NoAccess */
	size_t lldpV2RemManAddrLen;
	long lldpV2RemManAddrIfSubtype;	/* ReadOnly */
	ulong lldpV2RemManAddrIfId;	/* ReadOnly */
	oid *lldpV2RemManAddrOID;	/* ReadOnly */
	size_t lldpV2RemManAddrOIDLen;
};
struct lldpV2RemUnknownTLVTable_data {
	struct lldpV2RemUnknownTLVTable_data *lldpV2RemUnknownTLVTable_old;
	uint lldpV2RemUnknownTLVTable_rsvs;
	uint lldpV2RemUnknownTLVTable_tsts;
	uint lldpV2RemUnknownTLVTable_sets;
	uint lldpV2RemUnknownTLVTable_request;
	uint lldpV2RemUnknownTLVTable_refs;
	uint lldpV2RemUnknownTLVTable_id;
	long lldpV2RemTimeMark;		/* NoAccess */
	long lldpV2RemLocalIfIndex;	/* NoAccess */
	ulong lldpV2RemLocalDestMACAddress;	/* NoAccess */
	ulong lldpV2RemIndex;		/* NoAccess */
	ulong lldpV2RemUnknownTLVType;	/* NoAccess */
	uint8_t *lldpV2RemUnknownTLVInfo;	/* ReadOnly */
	size_t lldpV2RemUnknownTLVInfoLen;
};
struct lldpV2RemOrgDefInfoTable_data {
	struct lldpV2RemOrgDefInfoTable_data *lldpV2RemOrgDefInfoTable_old;
	uint lldpV2RemOrgDefInfoTable_rsvs;
	uint lldpV2RemOrgDefInfoTable_tsts;
	uint lldpV2RemOrgDefInfoTable_sets;
	uint lldpV2RemOrgDefInfoTable_request;
	uint lldpV2RemOrgDefInfoTable_refs;
	uint lldpV2RemOrgDefInfoTable_id;
	long lldpV2RemTimeMark;		/* NoAccess */
	long lldpV2RemLocalIfIndex;	/* NoAccess */
	ulong lldpV2RemLocalDestMACAddress;	/* NoAccess */
	ulong lldpV2RemIndex;		/* NoAccess */
	uint8_t *lldpV2RemOrgDefInfoOUI;	/* NoAccess */
	size_t lldpV2RemOrgDefInfoOUILen;
	ulong lldpV2RemOrgDefInfoSubtype;	/* NoAccess */
	ulong lldpV2RemOrgDefInfoIndex;	/* NoAccess */
	uint8_t *lldpV2RemOrgDefInfo;	/* ReadOnly */
	size_t lldpV2RemOrgDefInfoLen;
};

/* storage declarations */
extern struct lldpV2MIB_data *lldpV2MIBStorage;
extern struct header_complex_index *lldpV2PortConfigTableStorage;
extern struct header_complex_index *lldpV2DestAddressTableStorage;
extern struct header_complex_index *lldpV2ManAddrConfigTxPortsTableStorage;
extern struct header_complex_index *lldpV2StatsTxPortTableStorage;
extern struct header_complex_index *lldpV2StatsRxPortTableStorage;
extern struct header_complex_index *lldpV2LocPortTableStorage;
extern struct header_complex_index *lldpV2LocManAddrTableStorage;
extern struct header_complex_index *lldpV2RemTableStorage;
extern struct header_complex_index *lldpV2RemManAddrTableStorage;
extern struct header_complex_index *lldpV2RemUnknownTLVTableStorage;
extern struct header_complex_index *lldpV2RemOrgDefInfoTableStorage;

/* enum definitions from the covered mib sections */

#define LLDPV2PORTCONFIGADMINSTATUS_TXONLY       1
#define LLDPV2PORTCONFIGADMINSTATUS_RXONLY       2
#define LLDPV2PORTCONFIGADMINSTATUS_TXANDRX      3
#define LLDPV2PORTCONFIGADMINSTATUS_DISABLED     4

#define LLDPV2PORTCONFIGNOTIFICATIONENABLE_TRUE  1
#define LLDPV2PORTCONFIGNOTIFICATIONENABLE_FALSE 2

#define LLDPV2PORTCONFIGTLVSTXENABLE_PORTDESC    0
#define LLDPV2PORTCONFIGTLVSTXENABLE_SYSNAME     1
#define LLDPV2PORTCONFIGTLVSTXENABLE_SYSDESC     2
#define LLDPV2PORTCONFIGTLVSTXENABLE_SYSCAP      3

#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_OTHER 0
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_IPV4 1
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_IPV6 2
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_NSAP 3
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_HDLC 4
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_BBN1822 5
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_ALL802 6
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_E163 7
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_E164 8
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_F69 9
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_X121 10
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_IPX 11
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_APPLETALK 12
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_DECNETIV 13
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_BANYANVINES 14
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_E164WITHNSAP 15
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_DNS 16
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_DISTINGUISHEDNAME 17
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_ASNUMBER 18
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_XTPOVERIPV4 19
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_XTPOVERIPV6 20
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_XTPNATIVEMODEXTP 21
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_FIBRECHANNELWWPN 22
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_FIBRECHANNELWWNN 23
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_GWID 24
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_AFI 25
#define LLDPV2MANADDRCONFIGLOCMANADDRSUBTYPE_RESERVED 65535

#define LLDPV2MANADDRCONFIGTXENABLE_TRUE         1
#define LLDPV2MANADDRCONFIGTXENABLE_FALSE        2

#define LLDPV2LOCCHASSISIDSUBTYPE_CHASSISCOMPONENT 1
#define LLDPV2LOCCHASSISIDSUBTYPE_INTERFACEALIAS 2
#define LLDPV2LOCCHASSISIDSUBTYPE_PORTCOMPONENT  3
#define LLDPV2LOCCHASSISIDSUBTYPE_MACADDRESS     4
#define LLDPV2LOCCHASSISIDSUBTYPE_NETWORKADDRESS 5
#define LLDPV2LOCCHASSISIDSUBTYPE_INTERFACENAME  6
#define LLDPV2LOCCHASSISIDSUBTYPE_LOCAL          7

#define LLDPV2LOCSYSCAPSUPPORTED_OTHER           0
#define LLDPV2LOCSYSCAPSUPPORTED_REPEATER        1
#define LLDPV2LOCSYSCAPSUPPORTED_BRIDGE          2
#define LLDPV2LOCSYSCAPSUPPORTED_WLANACCESSPOINT 3
#define LLDPV2LOCSYSCAPSUPPORTED_ROUTER          4
#define LLDPV2LOCSYSCAPSUPPORTED_TELEPHONE       5
#define LLDPV2LOCSYSCAPSUPPORTED_DOCSISCABLEDEVICE 6
#define LLDPV2LOCSYSCAPSUPPORTED_STATIONONLY     7
#define LLDPV2LOCSYSCAPSUPPORTED_CVLANCOMPONENT  8
#define LLDPV2LOCSYSCAPSUPPORTED_SVLANCOMPONENT  9
#define LLDPV2LOCSYSCAPSUPPORTED_TWOPORTMACRELAY 10

#define LLDPV2LOCSYSCAPENABLED_OTHER             0
#define LLDPV2LOCSYSCAPENABLED_REPEATER          1
#define LLDPV2LOCSYSCAPENABLED_BRIDGE            2
#define LLDPV2LOCSYSCAPENABLED_WLANACCESSPOINT   3
#define LLDPV2LOCSYSCAPENABLED_ROUTER            4
#define LLDPV2LOCSYSCAPENABLED_TELEPHONE         5
#define LLDPV2LOCSYSCAPENABLED_DOCSISCABLEDEVICE 6
#define LLDPV2LOCSYSCAPENABLED_STATIONONLY       7
#define LLDPV2LOCSYSCAPENABLED_CVLANCOMPONENT    8
#define LLDPV2LOCSYSCAPENABLED_SVLANCOMPONENT    9
#define LLDPV2LOCSYSCAPENABLED_TWOPORTMACRELAY   10

#define LLDPV2LOCPORTIDSUBTYPE_INTERFACEALIAS    1
#define LLDPV2LOCPORTIDSUBTYPE_PORTCOMPONENT     2
#define LLDPV2LOCPORTIDSUBTYPE_MACADDRESS        3
#define LLDPV2LOCPORTIDSUBTYPE_NETWORKADDRESS    4
#define LLDPV2LOCPORTIDSUBTYPE_INTERFACENAME     5
#define LLDPV2LOCPORTIDSUBTYPE_AGENTCIRCUITID    6
#define LLDPV2LOCPORTIDSUBTYPE_LOCAL             7

#define LLDPV2LOCMANADDRSUBTYPE_OTHER            0
#define LLDPV2LOCMANADDRSUBTYPE_IPV4             1
#define LLDPV2LOCMANADDRSUBTYPE_IPV6             2
#define LLDPV2LOCMANADDRSUBTYPE_NSAP             3
#define LLDPV2LOCMANADDRSUBTYPE_HDLC             4
#define LLDPV2LOCMANADDRSUBTYPE_BBN1822          5
#define LLDPV2LOCMANADDRSUBTYPE_ALL802           6
#define LLDPV2LOCMANADDRSUBTYPE_E163             7
#define LLDPV2LOCMANADDRSUBTYPE_E164             8
#define LLDPV2LOCMANADDRSUBTYPE_F69              9
#define LLDPV2LOCMANADDRSUBTYPE_X121             10
#define LLDPV2LOCMANADDRSUBTYPE_IPX              11
#define LLDPV2LOCMANADDRSUBTYPE_APPLETALK        12
#define LLDPV2LOCMANADDRSUBTYPE_DECNETIV         13
#define LLDPV2LOCMANADDRSUBTYPE_BANYANVINES      14
#define LLDPV2LOCMANADDRSUBTYPE_E164WITHNSAP     15
#define LLDPV2LOCMANADDRSUBTYPE_DNS              16
#define LLDPV2LOCMANADDRSUBTYPE_DISTINGUISHEDNAME 17
#define LLDPV2LOCMANADDRSUBTYPE_ASNUMBER         18
#define LLDPV2LOCMANADDRSUBTYPE_XTPOVERIPV4      19
#define LLDPV2LOCMANADDRSUBTYPE_XTPOVERIPV6      20
#define LLDPV2LOCMANADDRSUBTYPE_XTPNATIVEMODEXTP 21
#define LLDPV2LOCMANADDRSUBTYPE_FIBRECHANNELWWPN 22
#define LLDPV2LOCMANADDRSUBTYPE_FIBRECHANNELWWNN 23
#define LLDPV2LOCMANADDRSUBTYPE_GWID             24
#define LLDPV2LOCMANADDRSUBTYPE_AFI              25
#define LLDPV2LOCMANADDRSUBTYPE_RESERVED         65535

#define LLDPV2LOCMANADDRIFSUBTYPE_UNKNOWN        1
#define LLDPV2LOCMANADDRIFSUBTYPE_IFINDEX        2
#define LLDPV2LOCMANADDRIFSUBTYPE_SYSTEMPORTNUMBER 3

#define LLDPV2REMCHASSISIDSUBTYPE_CHASSISCOMPONENT 1
#define LLDPV2REMCHASSISIDSUBTYPE_INTERFACEALIAS 2
#define LLDPV2REMCHASSISIDSUBTYPE_PORTCOMPONENT  3
#define LLDPV2REMCHASSISIDSUBTYPE_MACADDRESS     4
#define LLDPV2REMCHASSISIDSUBTYPE_NETWORKADDRESS 5
#define LLDPV2REMCHASSISIDSUBTYPE_INTERFACENAME  6
#define LLDPV2REMCHASSISIDSUBTYPE_LOCAL          7

#define LLDPV2REMPORTIDSUBTYPE_INTERFACEALIAS    1
#define LLDPV2REMPORTIDSUBTYPE_PORTCOMPONENT     2
#define LLDPV2REMPORTIDSUBTYPE_MACADDRESS        3
#define LLDPV2REMPORTIDSUBTYPE_NETWORKADDRESS    4
#define LLDPV2REMPORTIDSUBTYPE_INTERFACENAME     5
#define LLDPV2REMPORTIDSUBTYPE_AGENTCIRCUITID    6
#define LLDPV2REMPORTIDSUBTYPE_LOCAL             7

#define LLDPV2REMSYSCAPSUPPORTED_OTHER           0
#define LLDPV2REMSYSCAPSUPPORTED_REPEATER        1
#define LLDPV2REMSYSCAPSUPPORTED_BRIDGE          2
#define LLDPV2REMSYSCAPSUPPORTED_WLANACCESSPOINT 3
#define LLDPV2REMSYSCAPSUPPORTED_ROUTER          4
#define LLDPV2REMSYSCAPSUPPORTED_TELEPHONE       5
#define LLDPV2REMSYSCAPSUPPORTED_DOCSISCABLEDEVICE 6
#define LLDPV2REMSYSCAPSUPPORTED_STATIONONLY     7
#define LLDPV2REMSYSCAPSUPPORTED_CVLANCOMPONENT  8
#define LLDPV2REMSYSCAPSUPPORTED_SVLANCOMPONENT  9
#define LLDPV2REMSYSCAPSUPPORTED_TWOPORTMACRELAY 10

#define LLDPV2REMSYSCAPENABLED_OTHER             0
#define LLDPV2REMSYSCAPENABLED_REPEATER          1
#define LLDPV2REMSYSCAPENABLED_BRIDGE            2
#define LLDPV2REMSYSCAPENABLED_WLANACCESSPOINT   3
#define LLDPV2REMSYSCAPENABLED_ROUTER            4
#define LLDPV2REMSYSCAPENABLED_TELEPHONE         5
#define LLDPV2REMSYSCAPENABLED_DOCSISCABLEDEVICE 6
#define LLDPV2REMSYSCAPENABLED_STATIONONLY       7
#define LLDPV2REMSYSCAPENABLED_CVLANCOMPONENT    8
#define LLDPV2REMSYSCAPENABLED_SVLANCOMPONENT    9
#define LLDPV2REMSYSCAPENABLED_TWOPORTMACRELAY   10

#define LLDPV2REMREMOTECHANGES_TRUE              1
#define LLDPV2REMREMOTECHANGES_FALSE             2

#define LLDPV2REMTOOMANYNEIGHBORS_TRUE           1
#define LLDPV2REMTOOMANYNEIGHBORS_FALSE          2

#define LLDPV2REMMANADDRSUBTYPE_OTHER            0
#define LLDPV2REMMANADDRSUBTYPE_IPV4             1
#define LLDPV2REMMANADDRSUBTYPE_IPV6             2
#define LLDPV2REMMANADDRSUBTYPE_NSAP             3
#define LLDPV2REMMANADDRSUBTYPE_HDLC             4
#define LLDPV2REMMANADDRSUBTYPE_BBN1822          5
#define LLDPV2REMMANADDRSUBTYPE_ALL802           6
#define LLDPV2REMMANADDRSUBTYPE_E163             7
#define LLDPV2REMMANADDRSUBTYPE_E164             8
#define LLDPV2REMMANADDRSUBTYPE_F69              9
#define LLDPV2REMMANADDRSUBTYPE_X121             10
#define LLDPV2REMMANADDRSUBTYPE_IPX              11
#define LLDPV2REMMANADDRSUBTYPE_APPLETALK        12
#define LLDPV2REMMANADDRSUBTYPE_DECNETIV         13
#define LLDPV2REMMANADDRSUBTYPE_BANYANVINES      14
#define LLDPV2REMMANADDRSUBTYPE_E164WITHNSAP     15
#define LLDPV2REMMANADDRSUBTYPE_DNS              16
#define LLDPV2REMMANADDRSUBTYPE_DISTINGUISHEDNAME 17
#define LLDPV2REMMANADDRSUBTYPE_ASNUMBER         18
#define LLDPV2REMMANADDRSUBTYPE_XTPOVERIPV4      19
#define LLDPV2REMMANADDRSUBTYPE_XTPOVERIPV6      20
#define LLDPV2REMMANADDRSUBTYPE_XTPNATIVEMODEXTP 21
#define LLDPV2REMMANADDRSUBTYPE_FIBRECHANNELWWPN 22
#define LLDPV2REMMANADDRSUBTYPE_FIBRECHANNELWWNN 23
#define LLDPV2REMMANADDRSUBTYPE_GWID             24
#define LLDPV2REMMANADDRSUBTYPE_AFI              25
#define LLDPV2REMMANADDRSUBTYPE_RESERVED         65535

#define LLDPV2REMMANADDRIFSUBTYPE_UNKNOWN        1
#define LLDPV2REMMANADDRIFSUBTYPE_IFINDEX        2
#define LLDPV2REMMANADDRIFSUBTYPE_SYSTEMPORTNUMBER 3

/* notifications */
extern oid lldpV2RemTablesChange_oid[11];

/* scalars accessible only for notify */

/* object id definitions */
extern oid lldpV2TxRxCompliance_oid[11];
extern oid lldpV2TxCompliance_oid[11];
extern oid lldpV2RxCompliance_oid[11];
extern oid lldpV2ConfigGroup_oid[11];
extern oid lldpV2ConfigRxGroup_oid[11];
extern oid lldpV2ConfigTxGroup_oid[11];
extern oid lldpV2StatsRxGroup_oid[11];
extern oid lldpV2StatsTxGroup_oid[11];
extern oid lldpV2LocSysGroup_oid[11];
extern oid lldpV2RemSysGroup_oid[11];
extern oid lldpV2NotificationsGroup_oid[11];

/* function prototypes */
/* trap function prototypes */
extern void send_lldpV2RemTablesChange_v2trap(struct variable_list *);

/* variable function prototypes */
void init_lldpV2MIB(void);
void deinit_lldpV2MIB(void);
int term_lldpV2MIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_lldpV2MIB;
struct lldpV2MIB_data *lldpV2MIB_create(void);
struct lldpV2MIB_data *lldpV2MIB_duplicate(struct lldpV2MIB_data *);
int lldpV2MIB_destroy(struct lldpV2MIB_data **);
int lldpV2MIB_add(struct lldpV2MIB_data *);
void parse_lldpV2MIB(const char *, char *);
SNMPCallback store_lldpV2MIB;
void refresh_lldpV2MIB(int);
FindVarMethod var_lldpV2PortConfigTable;
struct lldpV2PortConfigTable_data *lldpV2PortConfigTable_create(void);
struct lldpV2PortConfigTable_data *lldpV2PortConfigTable_duplicate(struct lldpV2PortConfigTable_data *);
int lldpV2PortConfigTable_destroy(struct lldpV2PortConfigTable_data **);
int lldpV2PortConfigTable_add(struct lldpV2PortConfigTable_data *);
int lldpV2PortConfigTable_del(struct lldpV2PortConfigTable_data *);
void parse_lldpV2PortConfigTable(const char *, char *);
SNMPCallback store_lldpV2PortConfigTable;
void refresh_lldpV2PortConfigTable(int);
FindVarMethod var_lldpV2DestAddressTable;
struct lldpV2DestAddressTable_data *lldpV2DestAddressTable_create(void);
struct lldpV2DestAddressTable_data *lldpV2DestAddressTable_duplicate(struct lldpV2DestAddressTable_data *);
int lldpV2DestAddressTable_destroy(struct lldpV2DestAddressTable_data **);
int lldpV2DestAddressTable_add(struct lldpV2DestAddressTable_data *);
int lldpV2DestAddressTable_del(struct lldpV2DestAddressTable_data *);
void parse_lldpV2DestAddressTable(const char *, char *);
SNMPCallback store_lldpV2DestAddressTable;
void refresh_lldpV2DestAddressTable(int);
FindVarMethod var_lldpV2ManAddrConfigTxPortsTable;
struct lldpV2ManAddrConfigTxPortsTable_data *lldpV2ManAddrConfigTxPortsTable_create(void);
struct lldpV2ManAddrConfigTxPortsTable_data *lldpV2ManAddrConfigTxPortsTable_duplicate(struct lldpV2ManAddrConfigTxPortsTable_data *);
int lldpV2ManAddrConfigTxPortsTable_destroy(struct lldpV2ManAddrConfigTxPortsTable_data **);
int lldpV2ManAddrConfigTxPortsTable_add(struct lldpV2ManAddrConfigTxPortsTable_data *);
int lldpV2ManAddrConfigTxPortsTable_del(struct lldpV2ManAddrConfigTxPortsTable_data *);
void parse_lldpV2ManAddrConfigTxPortsTable(const char *, char *);
SNMPCallback store_lldpV2ManAddrConfigTxPortsTable;
void refresh_lldpV2ManAddrConfigTxPortsTable(int);
FindVarMethod var_lldpV2StatsTxPortTable;
struct lldpV2StatsTxPortTable_data *lldpV2StatsTxPortTable_create(void);
struct lldpV2StatsTxPortTable_data *lldpV2StatsTxPortTable_duplicate(struct lldpV2StatsTxPortTable_data *);
int lldpV2StatsTxPortTable_destroy(struct lldpV2StatsTxPortTable_data **);
int lldpV2StatsTxPortTable_add(struct lldpV2StatsTxPortTable_data *);
int lldpV2StatsTxPortTable_del(struct lldpV2StatsTxPortTable_data *);
void parse_lldpV2StatsTxPortTable(const char *, char *);
SNMPCallback store_lldpV2StatsTxPortTable;
void refresh_lldpV2StatsTxPortTable(int);
FindVarMethod var_lldpV2StatsRxPortTable;
struct lldpV2StatsRxPortTable_data *lldpV2StatsRxPortTable_create(void);
struct lldpV2StatsRxPortTable_data *lldpV2StatsRxPortTable_duplicate(struct lldpV2StatsRxPortTable_data *);
int lldpV2StatsRxPortTable_destroy(struct lldpV2StatsRxPortTable_data **);
int lldpV2StatsRxPortTable_add(struct lldpV2StatsRxPortTable_data *);
int lldpV2StatsRxPortTable_del(struct lldpV2StatsRxPortTable_data *);
void parse_lldpV2StatsRxPortTable(const char *, char *);
SNMPCallback store_lldpV2StatsRxPortTable;
void refresh_lldpV2StatsRxPortTable(int);
FindVarMethod var_lldpV2LocPortTable;
struct lldpV2LocPortTable_data *lldpV2LocPortTable_create(void);
struct lldpV2LocPortTable_data *lldpV2LocPortTable_duplicate(struct lldpV2LocPortTable_data *);
int lldpV2LocPortTable_destroy(struct lldpV2LocPortTable_data **);
int lldpV2LocPortTable_add(struct lldpV2LocPortTable_data *);
int lldpV2LocPortTable_del(struct lldpV2LocPortTable_data *);
void parse_lldpV2LocPortTable(const char *, char *);
SNMPCallback store_lldpV2LocPortTable;
void refresh_lldpV2LocPortTable(int);
FindVarMethod var_lldpV2LocManAddrTable;
struct lldpV2LocManAddrTable_data *lldpV2LocManAddrTable_create(void);
struct lldpV2LocManAddrTable_data *lldpV2LocManAddrTable_duplicate(struct lldpV2LocManAddrTable_data *);
int lldpV2LocManAddrTable_destroy(struct lldpV2LocManAddrTable_data **);
int lldpV2LocManAddrTable_add(struct lldpV2LocManAddrTable_data *);
int lldpV2LocManAddrTable_del(struct lldpV2LocManAddrTable_data *);
void parse_lldpV2LocManAddrTable(const char *, char *);
SNMPCallback store_lldpV2LocManAddrTable;
void refresh_lldpV2LocManAddrTable(int);
FindVarMethod var_lldpV2RemTable;
struct lldpV2RemTable_data *lldpV2RemTable_create(void);
struct lldpV2RemTable_data *lldpV2RemTable_duplicate(struct lldpV2RemTable_data *);
int lldpV2RemTable_destroy(struct lldpV2RemTable_data **);
int lldpV2RemTable_add(struct lldpV2RemTable_data *);
int lldpV2RemTable_del(struct lldpV2RemTable_data *);
void parse_lldpV2RemTable(const char *, char *);
SNMPCallback store_lldpV2RemTable;
void refresh_lldpV2RemTable(int);
FindVarMethod var_lldpV2RemManAddrTable;
struct lldpV2RemManAddrTable_data *lldpV2RemManAddrTable_create(void);
struct lldpV2RemManAddrTable_data *lldpV2RemManAddrTable_duplicate(struct lldpV2RemManAddrTable_data *);
int lldpV2RemManAddrTable_destroy(struct lldpV2RemManAddrTable_data **);
int lldpV2RemManAddrTable_add(struct lldpV2RemManAddrTable_data *);
int lldpV2RemManAddrTable_del(struct lldpV2RemManAddrTable_data *);
void parse_lldpV2RemManAddrTable(const char *, char *);
SNMPCallback store_lldpV2RemManAddrTable;
void refresh_lldpV2RemManAddrTable(int);
FindVarMethod var_lldpV2RemUnknownTLVTable;
struct lldpV2RemUnknownTLVTable_data *lldpV2RemUnknownTLVTable_create(void);
struct lldpV2RemUnknownTLVTable_data *lldpV2RemUnknownTLVTable_duplicate(struct lldpV2RemUnknownTLVTable_data *);
int lldpV2RemUnknownTLVTable_destroy(struct lldpV2RemUnknownTLVTable_data **);
int lldpV2RemUnknownTLVTable_add(struct lldpV2RemUnknownTLVTable_data *);
int lldpV2RemUnknownTLVTable_del(struct lldpV2RemUnknownTLVTable_data *);
void parse_lldpV2RemUnknownTLVTable(const char *, char *);
SNMPCallback store_lldpV2RemUnknownTLVTable;
void refresh_lldpV2RemUnknownTLVTable(int);
FindVarMethod var_lldpV2RemOrgDefInfoTable;
struct lldpV2RemOrgDefInfoTable_data *lldpV2RemOrgDefInfoTable_create(void);
struct lldpV2RemOrgDefInfoTable_data *lldpV2RemOrgDefInfoTable_duplicate(struct lldpV2RemOrgDefInfoTable_data *);
int lldpV2RemOrgDefInfoTable_destroy(struct lldpV2RemOrgDefInfoTable_data **);
int lldpV2RemOrgDefInfoTable_add(struct lldpV2RemOrgDefInfoTable_data *);
int lldpV2RemOrgDefInfoTable_del(struct lldpV2RemOrgDefInfoTable_data *);
void parse_lldpV2RemOrgDefInfoTable(const char *, char *);
SNMPCallback store_lldpV2RemOrgDefInfoTable;
void refresh_lldpV2RemOrgDefInfoTable(int);

WriteMethod write_lldpV2MessageTxInterval;
WriteMethod write_lldpV2MessageTxHoldMultiplier;
WriteMethod write_lldpV2ReinitDelay;
WriteMethod write_lldpV2NotificationInterval;
WriteMethod write_lldpV2TxCreditMax;
WriteMethod write_lldpV2MessageFastTx;
WriteMethod write_lldpV2TxFastInit;
WriteMethod write_lldpV2PortConfigAdminStatus;
WriteMethod write_lldpV2PortConfigNotificationEnable;
WriteMethod write_lldpV2PortConfigTLVsTxEnable;
WriteMethod write_lldpV2ManAddrConfigTxEnable;
WriteMethod write_lldpV2ManAddrConfigRowStatus;
#endif				/* __LOCAL_LLDPV2MIB_H__ */
